#!/bin/sh
#
#    Copyright (C) 2011  Santiago Rodríguez  <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
COMPONENT=main
. ./config

sed -i 's/Skype protocol" ON/Skype protocol" OFF/g' kopete/protocols/CMakeLists.txt

sed -i '/skype/d; /callto/d; /tel.protocol/d'  debian/kopete.install
rm -rf kopete/protocols/skype
sed 's/, Skype//' -i ./doc/kopete/index.docbook

changelog "Compiled for Trisquel" 

compile

