#!/bin/sh
#
#    Copyright (C) 2013  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2019 Mason Hock <mason@masonhock.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

rm -rf CommandNotFound/db/dists/$UPSTREAM*/multiverse
rm -rf CommandNotFound/db/dists/$UPSTREAM*/restricted

for word in restricted nonfree multiverse aee afio app-install-data-commercial app-install-data-partner b43-fwcutter bcm43xx-fwcutter chromium-codecs-ffmpeg chromium-browser d4x easycrypt gdecrypt envyng-core envyng-gtk envyng-qt fglrx-installer freesci gfxboot-theme-ubuntu pitfdll helix-player isdnactivecards isdnutils ivman jockey mame mesademos moon ndisgtk ndiswrapper nikto nvidia-common nvidia-graphics-drivers nvidia-graphics-drivers-173 nvidia-graphics-drivers-180 nvidia-graphics-drivers-71 nvidia-graphics-drivers-96 nvidia-settings nvidia-xconfig ophcrack rman simutrans-pak128.britain simutrans simutrans-pak64 scribus-ng-doc software-center starfighter tatan testdrive unetbootin ubuntuone-client ubuntu-restricted-extras rhythmbox-ubuntuone-music-store seamonkey ubuntuone-dev-tools libubuntuone ubuntuone-storage-protocol user-mode-linux user-mode-linux-doc vrms 9wm 9menu w9wm acetoneiso a2ps-perl-ja bibletime bibledit bible-kjv winetricks ; do
  /bin/sed "/name: .*$word.*/,+3d" -i CommandNotFound/db/dists/$UPSTREAM*/*/cnf/Commands-*
done

changelog "Removed references to non-free software"

compile

