#!/bin/sh
#
#    Copyright (C) 2021-2022  Ruben Rodriguez  <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

# Smaller clock size on panel
sed -i 's/main.height \* 0.56 : main.height \* 0.71/main.height * 0.4 : main.height * 0.4/' applets/digital-clock/package/contents/ui/DigitalClock.qml

# Use trisquel background
sed 's|/Next/contents/images/5120x2880.jpg|/Aramo/contents/images/5120x2880.jpg|' -i sddm-theme/theme.conf.cmake

changelog "Customized for Trisquel"

package

