#!/bin/sh
#
#    Copyright (C) 2009-2021  Rubén Rodríguez <ruben@gnu.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
NETINST=true
. ./config

sed -i 's/unattended-upgrades, landscape/unattended-upgrades/;
s/Install security updates automatically, Manage system with Landscape/Install security updates automatically/;
/By default, updates need to be applied manually using package management/d;
/tools. Alternatively, you can choose to have this system automatically/d;
/download and install security updates, or you can choose to manage this/d;
/system over the web as part of a group of systems using Canonical/d;
/Landscape service./d;' debian/pkgsel.templates

changelog "Rebranded and adapted for Trisquel"
compile
