#!/bin/sh
#
#    Copyright (C) 2020-2022  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

sed 's/eom .*,/viewnior,/' -i debian/control
sed 's/ubuntu-mate-themes |//' -i debian/control
sed 's/ubuntu-mate-wallpapers/trisquel-wallpapers/' -i debian/control
sed 's/thunderbird/icedove/' -i debian/control
sed 's/firefox/abrowser/' -i debian/control
sed 's/fonts-cantarell | fonts-ubuntu/fonts-trisquel/' -i debian/control

# https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/131
sed -i '/lock-delay=/s|1|0|' debian/10_mate-common.gschema.override

changelog "Default to Viewnior for image viewer | Match lock delay to mate-screensaver default value."

package

