#!/bin/sh
#
#    Copyright (C) 2012-2018 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
COMPONENT=main

. ./config

#Use custom apt-check to fix motd update notification by striping esm stuff.
cp $DATA/apt_check.py data/apt_check.py
sed -i '/test_motd.py/d' debian/rules
sed -i '/test_package-data-downloader.py/d' debian/rules

rm debian/update-notifier-hp-firmware.conf
sed '/hp-firmware/d' -i debian/update-notifier.install
sed -i "/ubuntu-drivers-common/d" debian/control

# Prevent automated connections
sed '/Update-Package-Lists/s/1/0/' -i debian/10periodic

changelog "Disabled hp-firmware handling and ubuntu-drivers"

compile
