#!/bin/sh
#
#    Copyright (C) 2018 Andrew M. Lindley <andrew@andrewlindley.co.uk>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

cat >>src/module.c <<EOF

#ifdef IRSSI_ABI_VERSION
/*
 * irssi abicheck()
 * From https://github.com/cryptodotis/irssi-otr/commit/d03ab59b6f27142c1c5e99fedc635a589b1607bb
 */
void otr_abicheck(int *version)
{
	*version = IRSSI_ABI_VERSION;
}
#endif
EOF

changelog "Added upstream commit to enable otr plugin #24166"

compile

