#!/bin/sh
#
#    Copyright (C) 2022  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu kinetic universe'

. ./config

# https://github.com/sugarlabs/sugar/issues/962
cat << EOF | patch --no-backup-if-mismatch -p1
--- a/src/jarabe/main.py	2022-04-23 02:53:15.000000000 -0400
+++ b/src/jarabe/main.py	2022-12-02 09:08:53.666508572 -0500
@@ -297,10 +297,6 @@
         os.environ['no_proxy'] = ",".join(Gio.Settings.new(
             'org.sugarlabs.system.proxy').get_strv('ignore-hosts'))
 
-    elif g_mode == 'none':
-        for each_env_variable in env_variables:
-            os.environ[each_env_variable] = ''
-
 
 def setup_theme():
     settings = Gtk.Settings.get_default()
EOF

changelog "Backported from kinetic"

package
