#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

cat << EOF > sweets.recipe
[DEFAULT]
depends   = base/dbus >= 0.95; base/dbus-glib >= 0.82
            base/glib >= 2.24; sdk/telepathy-glib >= 0.13.14
 
version   = 5.8.1
stability = stable
 
[Library]
implement = sdk/%(name)s
# Need custome MC w/o gnome-keyring support #2278
associate = base/%(name)s
name      = telepathy-mission-control
summary   = A Jabber/XMPP connection manager for Telepathy
license   = LGPLv2+
homepage  = http://telepathy.freedesktop.org/
 
requires  = %(depends)s
binding   = PATH bin
            PATH libexec
            LD_LIBRARY_PATH lib
            PKG_CONFIG_PATH lib/pkgconfig
            XDG_DATA_DIRS share
 
[Package]
project   = SweetsDistribution
 
[Archive]
arch      = any
 
[Build]
requires  = %(depends)s; base/xsltproc; base/python
            base/pkg-config; base/make; base/gcc-c
clean     = make clean
configure = ./configure
                --prefix=%(PREFIX)s
                --disable-gtk-doc
                --disable-gnome-keyring
                CFLAGS="%(CFLAGS)s"
make      = make
install   = make DESTDIR=%(DESTDIR)s install
 
[Source]
source    = telepathy-mission-control-%(version)s.tar.gz
EOF

changelog "Compiled for Trisquel On a Sugar TOAST"

compile
