#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2015  Francisco Javier Parra <franparpe@openmailbox.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=7

. ./config

rm debian/examples compton.sample.conf

cat << EOF >> debian/install
compton.conf /etc
compton-autostart.desktop /etc/xdg/autostart
compton-launcher /usr/bin
trisquel-compton-switcher /usr/bin
trisquel-compton-switcher.desktop /usr/share/applications
EOF


cp $DATA/compton.conf .
cp $DATA/compton-launcher .
cp $DATA/trisquel-compton-switcher .

cat << EOF > compton-autostart.desktop
[Desktop Entry]
Type=Application
Name=Compton composition manager
Exec=compton-launcher
NoDisplay=true
X-GNOME-AutoRestart=true
X-GNOME-Autostart-Phase=Initialization
OnlyShowIn=GNOME;
EOF

cat << EOF > trisquel-compton-switcher.desktop
[Desktop Entry]
Name=Compton compositor switcher
Comment=Allows to enable or disable Compton
Exec=trisquel-compton-switcher
Icon=checkbox
Terminal=false
Type=Application
StartupNotify=true
Categories=GNOME;Settings;DesktopSettings;
OnlyShowIn=GNOME;
Keywords=Compton;Compositing;Window manager;
X-Ubuntu-Gettext-Domain=trisquel-compton-switcher

Name[es]=Gestor del compositor Compton
Comment[es]=Permite activar o desactivar Compton
EOF

sed 's/^Depends:/Depends: mesa-utils, /' debian/control* -i
sed 's/^Depends:/Depends: zenity, /' debian/control* -i

chmod 755 compton-launcher
chmod 755 trisquel-compton-switcher

changelog "Customized for Trisquel"

compile

