#!/bin/bash
#
#    Copyright (C) 2015 Francisco Javier Parra <franparpe@openmailbox.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

EXTERNAL='deb-src http://ftp.es.debian.org/debian testing main'
PROFILES_TO_BE_DELETED="chromium-browser.profile chromium.profile \
dropbox.profile google-chrome.profile opera.profile skype.profile \
spotify.profile steam.profile"

VERSION=1

. ./config

# Modify profile for abrowser
mv etc/iceweasel.profile etc/abrowser.profile

# Delete any trace of proprietary software configuration
for PROFILE in $PROFILES_TO_BE_DELETED; do
rm etc/$PROFILE
done

# Delete proprietary software instances in the control file
sed 's/Chromium/Icecat/' platform/debian/control -i
sed 's/Opera,//' platform/debian/control -i

# Modify the conffiles to include modifications
sed '/chromium/d' platform/debian/conffiles -i
sed '/google/d' platform/debian/conffiles -i
sed '/opera/d' platform/debian/conffiles -i
sed '/skype/d' platform/debian/conffiles -i
sed '/spotify/d' platform/debian/conffiles -i
sed '/steam/d' platform/debian/conffiles -i
sed '/dropbox/d' platform/debian/conffiles -i

# Substitute Iceweasel for Abrowser in the conffiles
sed 's/iceweasel/abrowser/' platform/debian/conffiles -i

# Modify the makefile to cover the changes made to the source package
sed '/chromium/d' Makefile.in -i
sed '/google/d' Makefile.in -i
sed '/opera/d' Makefile.in -i
sed '/skype/d' Makefile.in -i
sed '/spotify/d' Makefile.in -i
sed '/steam/d' Makefile.in -i
sed '/dropbox/d' Makefile.in -i
sed 's/iceweasel/abrowser/' Makefile.in -i

# Changelog
changelog "Bringing firejail to Trisquel purging proprietary software references"

compile

