#!/bin/sh
#
#    Copyright (C) 2025 Kurt Kremitzki <kurt@kwk.systems>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=1
BUILD_UNTIL=12.0

# FreeCAD was not present in Debian Testing when Ubuntu 24.04 was released;
# jump forward to pull the version from 24.10
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu oracular universe'

. ./config

changelog "Package freecad for trisquel"
# Disable patches needed for Ubuntu 24.10 versions
remove_patch "0030-octt78.patch"
remove_patch "3000-vtk9.3.patch"
# Remove OpenCASCADE version pin associated with previous patch
sed -i 's/ (>= 7.8.1+dfsg1)//' debian/control

package
