#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

for driver in swift dectalk; do
  rm -rf drivers/$driver
  find | grep Makefile | xargs grep $driver |cut -d: -f1 | xargs sed "/SUBDIRS/s/$driver//" -i
  find | grep Makefile | xargs grep $driver |cut -d: -f1 | xargs sed "/$driver/d" -i
  find |grep $driver |grep -v templates|xargs rm
done

sed '/^ac_config_files/s:drivers/dectalk/Makefile::' -i configure
sed '/^ac_config_files/s:drivers/dectalk/GNOME_Speech_SynthesisDriver_Dectalk.server::' -i configure
sed '/^ac_config_files/s:drivers/swift/Makefile::' -i configure
sed '/^ac_config_files/s:drivers/swift/GNOME_Speech_SynthesisDriver_Swift.server::' -i configure

sed '/Package: gnome-speech-swift/,/system\./d' -i debian/control.in debian/control
sed '/Package: gnome-speech-dectalk/,/system\./d' -i debian/control.in debian/control
sed '/;  other backends that require proprietary/,/gnome-speech-swift/d' -i debian/control.in debian/control

changelog "Disable packaging of contrib packages gnome-speech-dectalk and gnome-speech-swift, Closes #2338"

compile

