#!/bin/sh
#
#    Copyright (C) 2022 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=0

. ./config

#Remove gnome-shell and notification-daemon dependency
sed -i 's/gnome-shell <!s390x> | //g' debian/control
sed -i 's/notification-daemon <!s390x>/policykit-1-gnome <!s390x>/g' debian/control

changelog "Remove gnome-shell and notification-daemon dependency from network-manager-gnome"

package
