#!/bin/sh
#
#    Copyright (C) 2026 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.


VERSION=1
EXTERNAL='deb-src http://deb.debian.org/debian trixie main'
REPOKEY=6ED0E7B82643E131
BACKPORTS=true
BUILD_UNTIL=12.0

. ./config

apply_patch_changes

changelog "Backport a more recent and usable tuba release from Trixie"

package
