#!/bin/sh
#
#    Copyright (C) 2022  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
. ./config

# Rebrand and tweak
grep -rl 'font-name='|xargs sed -i '/font-name/s|Ubuntu 11|Sans 11|'
replace ubuntu trisquel
replace Ubuntu Trisquel
find -type d |xargs rename s/ubuntu/trisquel/g
find -type f |xargs rename s/ubuntu/trisquel/g

#Themes
rm -r pocillo/IconRequests
cp $DATA/logo-trisquel.svg qogir-theme/src/gnome-shell/logos/
cp $DATA/logo-trisquel.svg qogir-theme/src/gtk/assets/logos/

changelog "Rebuild for trisquel"
compile
