#!/bin/sh
#
#    Copyright (C) 2019 Mason Hock <mason@masonhock.com>
#    Copyright (C) 2021 Pablo Correa Gómez <pcg@pcorreag.tk>
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
EXTERNAL='deb-src http://ppa.launchpad.net/scribus/ppa/ubuntu bionic main '
REPOKEY=B70D6F7664B6EE15
BACKPORTS=true

. ./config

# Revert (partial) removal of non-free patch
sed -i 's|^#remove_non-free_file.patch$|remove_non-free_file.patch|1' debian/patches/series
sed -i 's|^do-not-install-dicts$|#do-not-install-dicts|1' debian/patches/series

# Remove building non-free docs package
sed -i '/Package: scribus-doc/,$d' debian/control # scribus-doc is the last package in the control file

changelog "Backported from ppa"

changelog "Revert non-free parts of the package"

compile
