#!/bin/sh
#
#    Copyright (C) 2023 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=2

. ./config

# Replace icons
for i in ubuntu-logo-icon ubuntu-logo-dark
do
    replace $i TrisquelLogo
    rm debian/$i.png
done
cp $DATA/TrisquelLogo.png debian/TrisquelLogo.png

# Remove whoopsie/-preferences dependency from gnome-control-center
sed -i '/whoopsie-preferences/d' debian/control*
sed -i "/whoopsie/d" debian/rules
remove_patch diagnostics-Add-Whoopsie-support.patch

changelog "Rebrand for trisquel and remove whoopsie dependency."

compile
