#!/bin/sh
#
#    Copyright (C) 2012-2017  Ruben Rodriguuez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

# Get rid of /cow showing in the desktop
sed '/tmpfs/ s:$:\n/dev/loop1 /cow ext3 noauto 0 0:' scripts/casper-bottom/12fstab -i

# Only generate the locale selected at boot
sed 's/keep-existing/keep-existing $LANG/' -i scripts/casper-bottom/14locales

rm scripts/casper-premount/10driver_updates
rm scripts/casper-bottom/33enable_apport_crashes


changelog "Compiled for Trisquel"

compile

