#!/bin/sh
#
#    Copyright (C) 2023 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=0
EXTERNAL='deb-src http://ftp.us.debian.org/debian bookworm main'
REPOKEY=6ED0E7B82643E131
BACKPORTS=true
. ./config

# Set on a supported python version
sed -i "s|X-Python3-Version:.*|X-Python3-Version: >= 3.10|" debian/control

changelog "Imported into Trisquel"
compile
