#!/bin/bash
#
#    Copyright (C) 2008  Peter Stevenson
#    Copyright (C) 2008  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4

. ./config

#sed 's/replaced by e100/replaced by eepro100/' -i extra/modprobe.d/blacklist
#sed 's/blacklist eepro100/blacklist e100/' -i extra/modprobe.d/blacklist
echo "options b43 nohwcrypt=1 qos=0" > extra/modprobe.d/b43.conf
sed 's:\(cp extra/depmod.d/ubuntu.conf.*\):\1\n\tcp extra/modprobe.d/b43.conf $D/etc/modprobe.d/:' debian/rules -i

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${VERSION}'#p' debian/changelog)  "Added b43 config"

compile

