#!/bin/sh
#
#    Copyright (C) 2009-2010  Rubén Rodríguez <ruben@gnu.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://ftp.debian.org/debian bullseye main'
REPOKEY=648ACFD622F3D138
NETINST=true
. ./config


# getline "seed" file
getline(){
grep -n "$1" "$2" |tail -n 1 |cut -d: -f1
}

START=$(getline "Template: hw-detect/load_media" debian/hw-detect.templates)
END=$(getline "If you have such media available now, insert it, and continue." debian/hw-detect.templates)
sed ${START},${END}d debian/hw-detect.templates -i

sed -i '/non-free/,/^fi$/ d'  hw-detect.post-base-installer.d/50install-firmware

changelog "Rebranded and adapted for Trisquel"
compile
