#!/bin/sh
#
#    Copyright (C) 2012  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
COMPONENT=main

. ./config

#cp $DATA/99_trisquel_defaults.patch debian/patches
#echo 99_trisquel_defaults.patch >> debian/patches/series
#sed -i 's/ubuntu-software-center/gnome-app-install/' debian/patches/09_app_install_entry.patch

for i in 03_kde-legacydirs.patch 05_debian_menu.patch 09_app_install_entry.patch 09_games-menu.patch 11_science-menu.patch
do
  rm debian/patches/$i
  sed /$i/d -i debian/patches/series
done

cp $DATA/applications.menu layout/applications.menu

changelog "Default layout adapted for Trisquel"

compile

