#!/bin/sh
#
#    Copyright (C) 2012  Santiago Rodríguez  <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
COMPONENT=main
. ./config

#Add support for theunarchiver, patch by Luke Shumaker
# https://svn.reviewboard.kde.org/r/6730/
patch -p0 < $DATA/ark-unarchiver-03.patch

#Drop support for non-free rar 
sed -i 's/add_subdirectory( clirarplugin )//g' ark/plugins/CMakeLists.txt
rm -rf ark/plugins/clirarplugin/
sed -i 's/clirar/cliunarchiver/g' debian/ark.install

#
# Limitations 
#
#  01 - cannot extract just one file from the archive
#  02 - overwrites existing files without prompt
#  03 - cannot edit archives
#  04 - if a wrong password is given, it fails (usually segfaults)  without telling what went wrong

changelog "Add support for theunarchiver" 

compile

