#!/bin/sh
#
#    Copyright (C) 2015  Santiago Rodríguez <santi@trisquel.info>
#    Copyright (C) 2021  Pablo Correa Gómez <ablocorrea@hotmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

patch -p1 < $DATA/bleachbit-FSDG.patch

# Non-free programs. Remove to avoid advertisement
for CLEANER in adobe_reader amsn chromium discord flash google_chrome google_earth google_toolbar internet_explorer microsoft_office opera paint realplayer safari secondlife_viewer silverlight skype smartftp teamviewer winamp windows_defender windows_explorer windows_media_player winrar winzip wordpad yahoo_messenger
do
	rm -v cleaners/$CLEANER.xml
done

replace Firefox Abrowser .
replace firefox abrowser .

#Icecat.xml based on
# https://gist.githubusercontent.com/BrunoReX/5286414/raw/82100ae69a7a896f3626e8011bf4c2abf6323ab2/firefox.xml

cp $DATA/icecat.xml cleaners/icecat.xml

changelog "Rename firefox to abrowser"

changelog "Add icecat cleaner"

changelog "Remove cleaners for non-free programs and stop advertising them"

compile
