#!/bin/sh
#
#    Copyright (C) 2012  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

#patch -p1 < $DATA/harcoded_orca.patch
#patch -p1 < $DATA/no_dots.patch
sed s/ubuntu/gnome-classic/g src/unity-greeter.vala -i
rm src/*.c

#% REBRAND: Replace the logo
#% CurrentState: 
#% ExpectedState:
cp $DATA/logo.png data

#% Set default background color to black
replace 2C001E 000000 .

#% Addapt default settings to Trisquel
cat << EOF > data/unity-greeter.conf
#
# background = Background file to use, either an image path or a color (e.g. #772953)
# logo = Logo file to use
# theme-name = GTK+ theme to use
# font-name = Font to use
# xft-antialias = Whether to antialias Xft fonts (true or false)
# xft-dpi = Resolution for Xft in dots per inch (e.g. 96)
# xft-hintstyle = What degree of hinting to use (hintnone, hintslight, hintmedium, or hintfull)
# xft-rgba = Type of subpixel antialiasing (none, rgb, bgr, vrgb or vbgr)
#
[greeter]
background=/usr/share/backgrounds/dagda-g.jpg
logo=/usr/share/unity-greeter/logo.png
theme-name=Trisquel
icon-theme-name=trisquel
font-name=Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
EOF

changelog "Adapted for Trisquel"

compile
