#!/bin/sh
#
#    Copyright (C) 2011 MPA
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4

. ./config

tmp=`mktemp`
printers='data/models/models.dat'

grep -B 7 'download=True' $printers|grep "\["|sed 's/\[//g; s/\]//g' > $tmp
for i in `cat $tmp`; do 
	sed -i '/\['"$i"'\]/,/^$/d' $printers
done
sed -i 's/plugin=2/plugin=0/g' $printers

rm $tmp

rm debian/patches/hp_photosmart_pro_b9100_support.dpatch
sed -i '/hp_photosmart_pro_b9100_support.dpatch/d' debian/patches/00list

changelog "Removed printers with propietary drivers (required and optional)"

compile
