#!/bin/sh
#
#    Copyright (C) 2015  Santiago Rodríguez <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

sed -i 's/Firefox/Abrowser/g' bleachbit/Cleaner.py
sed -i 's/firefox/abrowser/g' bleachbit/Cleaner.py

#Icecat.xml based on
# https://gist.githubusercontent.com/BrunoReX/5286414/raw/82100ae69a7a896f3626e8011bf4c2abf6323ab2/firefox.xml

cp $DATA/icecat.xml cleaners/icecat.xml

changelog "Updates for Trisquel"

compile
