#!/bin/sh
#
#    Copyright (C) 2024  Luis Guzmán <ark@switnet.org>
#    Copyright (C) 2012-2022  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

#STAGE-1-DEBOOTSTRAP

VERSION=5
COMPONENT=main

. ./config

cat << EOF > scripts/t/origins/trisquel
Vendor: Trisquel
Vendor-URL: http://trisquel.info/
Bugs: https://gitlab.trisquel.org/groups/trisquel/-/issues
Parent: Ubuntu
EOF

cp scripts/t/Dpkg_BuildFlags_Ubuntu.t scripts/t/Dpkg_BuildFlags_Trisquel.t
cp scripts/t/Dpkg_Changelog_Ubuntu.t scripts/t/Dpkg_Changelog_Trisquel.t
sed 's/Ubuntu/Trisquel/g' -i scripts/t/Dpkg_BuildFlags_Trisquel.t

# Patch a copy from the Ubuntu.pm file to force track changes more often,
# and rebuild easier the original changes.
cp scripts/Dpkg/Vendor/Ubuntu.pm scripts/Dpkg/Vendor/Trisquel.pm
patch_p1 $DATA/patch-Trisquel_pm-from-Ubuntu_pm.patch

# Use patch to track changes at Makefile.{in,am} files.
patch_p1 $DATA/patch-Makefile_in_am-to-add-trisquel-options.patch

# Trisquel.pm in now here, not at trisquel-base-data
sed '/Package: libdpkg-perl/,/^$/s/Depends:/Replaces: trisquel-base-data\nDepends:/' -i debian/control

changelog "Compiled for Trisquel"

package

