#!/bin/sh
#
#    Copyright (C) 2008-2022  Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C) 2022 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
COMPONENT=main

. ./config

cp data/50unattended-upgrades.Ubuntu data/50unattended-upgrades.Trisquel
sed -i '/ESM/d' data/50unattended-upgrades.Trisquel
echo "82db2ae24442f1e1684243a71a78e7de" >> data/50unattended-upgrades.md5sum

# Disable by default
sed '/Template: unattended-upgrades.enable_auto_updates/,/Default/s/Default: true/Default: false/' -i ./debian/templates

changelog "Compiled for Trisquel"

compile

