#!/bin/sh
#
#    Copyright (C) 2008-2012  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
COMPONENT=main
QUILT=skip

. ./config

for i in 50_ubuntu_sessions.patch 52_xdg_current_desktop.patch; do
    rm debian/patches/$i
    sed "/$i/d" -i debian/patches/series
done

export QUILT_PATCHES=debian/patches
quilt push -a

rm debian/ubuntu-session.*
sed '/Package: ubuntu-session/,/^$/d' debian/control -i

changelog "Adapted for Trisquel"

compile

