#!/bin/sh
#
#    Copyright (C) 2022  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA


VERSION=2
COMPONENT=main

. ./config

sed 's/# (theme "Dark")/(theme "System")/' -i etc/gimprc.in
sed 's/# (icon-theme "Symbolic")/(icon-theme "Color")/' -i etc/gimprc.in
sed 's/(icon-theme "Symbolic")/(icon-theme "Color")/' -i docs/gimprc.5.in
sed '/DEFAULT_ICON_THEME/s/Symbolic/Color/' -i app/config/gimpguiconfig.h libgimpwidgets/gimpicons.c


changelog "Use system gtk theme and color icons"

package

