#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
COMPONENT=main

. ./config

sed -i '/+NotShowIn/s|;GNOME;|;|g' debian/patches/Hide-Printers-app-in-GNOME-and-KDE.patch \
                                  debian/patches/Do-not-autostart-the-applet-on-LXDE-or-Unity.patch

remove_patch Allow-installing-non-free-drivers-from-OpenPrinting.patch
remove_patch Allow-installing-packages-from-OpenPrinting.patch

#mkdir debian/local/
#cp $DATA/testpage* debian/local/

#Recommend trisquel-app-installer over gnome-software
sed 's|gnome-software.*|trisquel-app-install,|g' -i debian/control

changelog "Compiled for Trisquel"

compile

