#!/bin/sh
# Copyright (C) 2018  Jorge Maldonado Ventura <jorgesumle@freakspot.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

VERSION=2

. ./config

rm debian/patches/0001-Debian-server-defaults.patch
sed '/Debian-server/d' -i debian/patches/series
#Apply patch with changes
sed '/0002/i 0001-Ubuntu-server-defaults.patch' -i debian/patches/series

# Suggest #trisquel IRC channel
sed 's|#ubuntu|#trisquel|g' -i debian/patches/0001-Ubuntu-server-defaults.patch

changelog "Compiled for Trisquel default channel #trisquel"

compile
