#!/bin/sh
#
#    Copyright (C) 2015 fr33domlover <fr33domlover@riseup.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=1

. ./config

HTML_FILE=debian/index.html

sed -i 's~Ubuntu\sBug\sTracking\sSystem~upstream bug tracker~g' $HTML_FILE
sed -i 's~Ubuntu~Trisquel GNU/Linux~g'                          $HTML_FILE
sed -i 's~packages\.ubuntu\.com~packages.trisquel.info~g'       $HTML_FILE

changelog "Fix Ubuntu references in the default index.html"

package
