#!/bin/bash
#
#    Copyright (C) 2008  Peter Stevenson
#    Copyright (C) 2009  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

egrep -lr 'X-AppInstall-Section=(multiverse|restricted)' . | xargs -r rm
for i in firefox* vlc nvidia* jockey* envyng* helix* ubufox ubuntu* ndisgtk*
do  
    rm -v menu-data/$i
done

#cp $WD/DATA/gnome-app-install/* ./menu-data/

sed 's/\(^Architecture: all$\)/\1\nReplaces: trisquel-app-install (<< 2.2)\nConflicts: trisquel-app-install (<< 2.2)/' -i debian/control

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${VERSION}'#p' debian/changelog)  "Removed non-free recommendation system"

compile

