#!/bin/sh
#
#    Copyright (C) 2011  Santiago Rodríguez <aklis@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

sed -i  '/Suggests: p7zip-rar/d'  debian/control 
#Our versions doesn't handle rar files, due to licenses
sed -i 's/RAR, ARJ,/ARJ,/g' debian/control
#
changelog "Remove non free suggests"
#Closes https://trisquel.info/es/issues/4360
compile

