#!/bin/sh
#
#    Copyright (C) 2015 fr33domlover <fr33domlover@riseup.net>
#    Copyright (C) 2021 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=2

. ./config

sed -i 's|Firefox, Chrome, Safari, or Opera|GNU IceCat, Abrowser, Epiphany, or Midori|g' src/dotfilepatcher.cpp
sed -i 's|Firefox, Chrome, Safari, or Opera|GNU IceCat, Abrowser, Epiphany, or Midori|g' src/htmldocvisitor.cpp
sed -i 's|Firefox, Chrome, Safari, and Opera|GNU IceCat, Abrowser, Epiphany|g' src/config.xml
sed -i 's|Mozilla Firefox, Google Chrome, Safari|GNU IceCat, Abrowser, Epiphany|g' doc/starting.doc
find . -type f -exec sed -i 's|Firefox|Abrowser|g' {} +

changelog "Replace references to nonfree browsers to freedom respecting ones"

compile
