#!/bin/sh
#
#    Copyright (C) 2021  Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C) 2019  Mason Hock <mason@masonhock.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4

. ./config

sed 's/OnlyShowIn=Unity;/OnlyShowIn=Unity;MATE;/' -i a11y-profile-manager-indicator-autostart.desktop.in

cat << EOF >> profiles/blindness/profile.gsettings

[com.canonical.unity-greeter]
screen-reader=true
EOF

cat << EOF >> profiles/onscreen-keyboard/profile.gsettings

[com.canonical.unity-greeter]
onscreen-keyboard=true
EOF

cat << EOF >> profiles/high-contrast/profile.gsettings

[com.canonical.unity-greeter]
high-contrast=true
EOF

sed 's/orca/orca --replace/' -i profiles/blindness/profile.manifest.in

changelog "Added unity-greeter gsettings"

compile

