#!/bin/sh
#
#    Copyright (C) 2022 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=0
#Step one - build 1.60
EXTERNAL='deb-src http://ftp.debian.org/debian testing main'
REPOKEY=648ACFD622F3D138
#Step two - build 1.61
#EXTERNAL='deb-src http://ppa.launchpadcontent.net/ubuntu-mozilla-security/rust-updates/ubuntu $UPSTREAM main'
#REPOKEY=A6DCF7707EBC211F
BACKPORTS=true
. ./config


changelog "Import as dependency of newer abrowser deb dependencies."

compile
