#!/bin/sh
#
#    Copyright (C) 2019 David Philipe GIl <davidpgil@protonmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
#

VERSION=1
EXTERNAL='deb-src http://ppa.launchpad.net/ubuntuhandbook1/dvdstyler/ubuntu focal main'
REPOKEY=A0062203196CA4482DDB859E4C1CBE14852541CB
BACKPORTS=true
DEPENDS=wxsvg

. ./config

changelog "Backported from ppa"

compile

