#!/bin/sh
#
#    Copyright (C) 2018 Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C) 2018 Pablo Correa Gómez <p.correag@member.fsf.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#

VERSION=2

. ./config

sed 's|can optionally be|is installed in /etc and can optionally be|1' -i debian/redshift.5

cat << EOF > debian/redshift.conf
; Global settings
[redshift]
temp-day=5700
temp-night=3500
transition=1
gamma=1:1:1

; WARNING: Changing provider to geoclue2 will set lat and lon
; automatically, but it will trigger background internet connections
location-provider=manual
; location-provider=geoclue2
adjustment-method=vidmode

; The location provider and adjustment method settings
; are in their own sections.
[manual]
lat=0.0
lon=0.0

; Numbering starts from 0, and refers to screen number,
; so this is actually the first screen.
[vidmode]
screen=0
 
EOF
echo "debian/redshift.conf /etc" >> debian/redshift.install

changelog "Added default manual configuration"

compile
