#!/bin/sh
#
#    Copyright (C) 2015  Santiago Rodríguez <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

sed -i  's/changelogs\.ubuntu\.com/packages\.trisquel\.org/g' debian/patches/04_changelog
sed -i 's/Ubuntu/Trisquel/g' debian/patches/04_changelog

# Note: i386 rebuild requires no change on helper or other helpers as binaries can be
# easily recompiled from the jenkins dashboard by arch specific, avoiding helpers

changelog "Imported into Trisquel"
package
