#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2025       Jacob K <jacobk@disroot.org>
#    Copyright (C) 2025       Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

# Apply patches for screen reader on in pidgin, see more at:
# https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/198

apply_patch_changes


changelog "
Apply fix for issue TPH#198 for using pidgin with the screen reader.
Apply fix for pidgin not able to access ibus socket
"

package
