#!/bin/sh
#
#    Copyright (C) 2008-2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
NETINST=true

. ./config

echo "quz;Quechua;Qhiswa (Cuzco-Collao);1;PE;UTF-8;quz_PE.UTF-8;;console-setup" >> languagelist
echo "aym;Aymara;Aymara;1;PE;UTF-8;aym_PE.UTF-8;;console-setup" >> languagelist

changelog "Added quz_PE and aym_PE locales"

compile

