#!/bin/sh
#
#    Copyright (C) 2011  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
FAKEROOT=true

. ./config

rm debian/patches/ -rf

cat << EOF > data/config/settings.ini
[plugins]
enabled = L: ['equalizer', 'lyricsviewer', 'shoutcast', 'lyricwiki', 'cd', 'massstorage', 'notifyosd', 'ipod', 'gnomemmkeys' ]

[osd]
enabled = B: False
hover_tray = B: False

[covers]
preferred_order = L: ['local', 'lastfm']

[cd_import]
format = S: FLAC

[gui]
use_tray = B: True
minimize_to_tray = B: True
use_splash = B: False
EOF

FILE=data/exaile.desktop

echo 'Comment[es]=Escuche, explore o gestione su colección de música' >> $FILE
echo 'Comment[gl]=Escoite, explore ou xestione a súa colección de música' >> $FILE
echo 'GenericName[es]=Reproductor de música' >> $FILE
echo 'GenericName[gl]=Reproductor de música' >> $FILE
echo 'X-GNOME-FullName[es]=Reproductor de música Exaile' >> $FILE
echo 'X-GNOME-FullName[gl]=Reproductor de música Exaile' >> $FILE

changelog "Default settings changed for Trisquel"

compile

