#!/bin/sh
#
#    Copyright (C) 2025  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu resolute universe'
REPOKEY=871920D1991BC93C
BUILD_UNTIL=12.0

. ./config

FULLVERSION=$(sed -E 's/^(.*)build([0-9]+)trisquel([0-9]+)$/\1trisquel\3~build\2/' <<< $FULLVERSION)
# Build until T12 if patches are not backported later on T13.
apply_patch_changes

changelog "Upgrade Ecne's version to manage apt 3.0 upgrade"

package

