#!/bin/sh
#
#    Copyright (C) 2022 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
BUILD_UNTIL=11.0

. ./config

# Remove helper once upstream version is 1.5.27 or later.

# Add missing file on tarball (1.5.26)
cp $DATA/denylist.txt engine/
# Apply patch to fix removal of Latin American Spanish
patch --no-backup-if-mismatch -p1 < $DATA/fix_latam_spanish_blacklist.patch
patch --no-backup-if-mismatch -p1 < $DATA/simple.xml.in_1.5.27.patch

changelog "Fix missing latam keyboard layout."

package
