#!/bin/sh
#
#    Copyright (C) 2023 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=5
EXTERNAL='deb-src http://ftp.debian.org/debian bullseye-backports main'
REPOKEY=0E98404D386FA1D9
BACKPORT=true

. ./config

# Apply patches to use system's libsrtp2
for patch in $(ls -v ${DATA}/*.patch)
do
    echo "Applying $patch"
    patch --no-backup-if-mismatch -Np1 < $patch
done

# Manually remove third_party src
rm -r src/third_party/libsrtp

changelog "Applied libsrtp system usage update to bullseye-backports."

package
