#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2021  Pablo Correa Gómez <ablocorrea@hotmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

#% Replace default applications in /usr/share/applications/defaults.list (makes icecat appear in gnome-default-applications-properties)
sed 's/firefox/abrowser/g; s/snap-store_ubuntu-software-local-file/gdebi/g; s/banshee/vlc.desktop/g;' -i debian/defaults.list

changelog "Rebranded for Trisquel"

package
