#!/bin/sh
#
#    Copyright (C) 2014-2018  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

EXTERNAL='deb-src http://ftp.us.debian.org/debian oldstable main'
REPOKEY=7638D0442B90D010

. ./config

rm debian/contrib/debianpowered.png
cp $DATA/trisquelpowered.png debian/contrib/
replace debianpowered trisquelpowered .
sed '/SITE_URL/s/www.debian.org/trisquel.info/; s/Debian Powered/Trisquel GNU\/Linux Powered/' -i debian/patches/25_site_logo.patch

changelog "Rebranded for Trisquel"

compile

