#!/bin/sh
#
#    Copyright (C) 2014  Legimet
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu focal universe'

. ./config

# Remove references to nonfree firmware blob
rm debian/fetch-openline-firmware

sed -i '/./{H;$!d;};x;/firmware/d;' debian/copyright
sed -i '1d' debian/copyright
echo >> debian/copyright

sed -i '/./{H;$!d;};x;/firmware/d;' debian/README.Debian
sed -i '1d' debian/README.Debian
echo >> debian/README.Debian

sed -i '/fetch-openline-firmware/d' debian/rules

changelog "Move to a supported version for Linux kernel 4.15 trisquel2 ||
Remove references to nonfree blob, fixes #10980 trisquel1"

compile
