#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=5
COMPONENT=main

. ./config

# remove gconf defaults to avoid conflicting with trisquel's
sed '/default/d; /gconf/d;' -i debian/rules

cp $DATA/gnome-panel.patch debian/patches/01_layout.patch

cat << EOF | patch -p1
--- gnome-panel-2.32.1.orig//applets/notification_area/na-tray-child.c  2010-09-02 08:29:09.000000000 +0000
+++ gnome-panel-2.32.1/applets/notification_area/na-tray-child.c        2011-08-04 13:23:33.000000000 +0000
@@ -131,6 +131,12 @@
                              GtkAllocation  *allocation)
 {
   NaTrayChild *child = NA_TRAY_CHILD (widget);
+
+  //hack to fix icon sizes to 24x24
+  allocation->y=round((allocation->height - 24)/2);
+  allocation->width=24;
+  allocation->height=24;
+
   GtkAllocation widget_allocation;
   gboolean moved, resized;
EOF

changelog "Compiled for Trisquel"

compile

