#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://ppa.launchpad.net/stebbins/handbrake-snapshots/ubuntu/ $UPSTREAM main'

cat << EOF | apt-key add -
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.4
Comment: Hostname: keyserver.ubuntu.com

mI0ES8Yj/gEEAND+ODU2t3ZahKHDlM0N5DuPqh5cytE+KA68aRbFXYXUjNHkjcocQ8pEYRJk
mVijbmYQs+wumvvJYLmXmOLXO3uQlBdL9wWaw2njx8f02JnZE1OSdO0Fo/b6BFEsKvusW5Kx
SAsjeXAKIVQFN3FDxQu12nZ1bgUSLihpGcxcRlmhABEBAAG0HUxhdW5jaHBhZCBIYW5kQnJh
a2UgU25hcHNob3RziLYEEwECACAFAkvGI/4CGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAK
CRCHca2wgWlQ2AKrA/46OaXTBunekpRF8aZUZI2+4e6vI8rGqJZECnar8UVyKnBR42xzLx5D
9G7KlAtkyFYYyUN2Mzm/AfCgvcD+4Q/+E7LV3G/yVYaDpyhqf1ulcHE881sU63JqZP+E4L3f
3wZ6eyNYUWx84lH/3ui/U07zNDqheIcQsSOdpBD6S1LffA==
=Pqya
-----END PGP PUBLIC KEY BLOCK-----
EOF

. ./config

changelog "Imported into Trisquel"

compile

