#!/bin/sh
#
#    Copyright (C) 2012  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
COMPONENT=main
QUILT=skip

. ./config

sed 's/--enable-magic/--enable-magic --disable-packagekit/' debian/rules -i
rm debian/patches/01_package_names.patch
sed '/^01_package_names\.patch/d' debian/patches/series -i

export QUILT_PATCHES=debian/patches
quilt push -a

changelog "Disabled package recommendations, fixes #7747"

compile

