#!/bin/sh
#
#    Copyright (C) 2019 Mason Hock <mason@masonhock.com>
#    Copyright (C) 2020 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
EXTERNAL='deb-src http://ppa.launchpad.net/thomas-schiex/blender/ubuntu bionic main '
REPOKEY=7281E3E842A98114
BACKPORTS=true
DEPENDS=openimageio,openshadinglanguage,openjpeg,opencollada,opensubdiv

. ./config
sed -i "s|debhelper (>= 7.0.50\~)|debhelper (<< 12\~)|" debian/control

#By removing these libraries/features is possible to build other arch rather amd64-only
sed -i "s|openimagedenoise,||" debian/control
sed -i "s|libalembic-dev,||" debian/control

changelog "Backported from ppa and remove 64bits-only dependencies"

compile
