#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu $UPSTREAM multiverse'

TMPFILE=$(mktemp)
cp /etc/apt/sources.list $TMPFILE
echo "deb http://archive.ubuntu.com/ubuntu lucid multiverse" >> /etc/apt/sources.list
apt-get update
apt-get install -y --yes libmp3lame-dev
mv $TMPFILE /etc/apt/sources.list

. ./config

changelog "Imported into Trisquel"

compile

