#!/bin/sh
#
#    Copyright (C) 2012  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
FAKEROOT=true

. ./config

sed '/x86_64-linux-gnu/,/endif/ d' debian/rules -i

cat << EOF > scripts/t/origins/trisquel
Vendor: Trisquel
Vendor-URL: http://trisquel.info/
Bugs: https://trisquel.info/en/project/issues
Parent: Ubuntu
EOF

cat << EOF >> scripts/t/600_Dpkg_Changelog_Trisquel.t
# -*- perl -*-
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;

\$ENV{DEB_VENDOR} = 'Trisquel';
my \$srcdir = \$ENV{srcdir} || '.';
do "\$srcdir/t/600_Dpkg_Changelog.t";
EOF

cp $DATA/Trisquel.pm scripts/Dpkg/Vendor/Trisquel.pm


changelog "Multiarch disabled by default"

compile

