#!/bin/sh
#
#    Copyright (C) 2020  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

patch -p1 < $DATA/122a6cd8_correct_handling_of_removable_file_systems.patch
patch -p1 < $DATA/d735708f_update_mount_point_after_mount_operations.patch

changelog "Correct handling of removable file systems KDE GIT#122a6cd8 & #d735708f"

compile

