#!/bin/sh
#
#    Copyright (C) 2025  Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
EXTERNAL='deb-src http://deb.debian.org/debian sid main'
REPOKEY=6ED0E7B82643E131
BACKPORTS=true
. ./config

SUPPORTED_SITES="https://ytdl-org.github.io/youtube-dl/supportedsites.html"
LAST_SUPPORTED="$(tail -n1 debian/control|sed 's|^ ||')"

sed -i "/Currently supported/s|are:|are at:|" debian/control
/bin/sed -n -i '/Currently supported/{p;:a;N;/'$LAST_SUPPORTED'/!ba;s| .*| '$SUPPORTED_SITES'\n|};p' debian/control
# Make sure it fails if we don't get the wanted output.
[ "$SUPPORTED_SITES" != "$(tail -n2 debian/control|awk NF|sed 's|^ ||')" ] && \
  echo -e ">>>Site replacement needs fixing, exiting...<<<\n" && exit

apply_patch_changes

changelog "Remove explicit site listing, redirecting to website author."

package
