#!/bin/sh
#
#    Copyright (C) 2025  Luis Guzman <ark@switnet.org>
#    Copyright (C) 2022  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3.1
EXTERNAL='deb-src http://ftp.debian.org/debian trixie main'
REPOKEY=6ED0E7B82643E131
NETINST=true

. ./config

replace grub-efi-amd64-signed grub-efi-amd64

sed 's/shim-signed/shim/' -i grub-installer

# Apply patches for this release
apply_patch_changes

changelog "Remove grub-efi-amd64-signed dependency. | Non-fatal fail if mkdir efivars fails."

package
