#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
EXTERNAL='deb-src http://ppa.launchpad.net/gnuzilla-team/ppa/ubuntu $UPSTREAM main'

. ./config

sed 's/Package: icecat-\(.*\)/Package: icecat-\1\nProvides: firefox-locale-\1/g' debian/control -i

cat << EOF > debian/rules
#!/usr/bin/make -f

%:
	dh \$@

override_dh_auto_clean:
	dh_auto_clean
	rm -rf build

override_dh_auto_build:
	sh debian/build-script.sh \$@
	sh debian/build-post-script.sh \$@

override_dh_auto_install:
	sh debian/build-script.sh \$@
EOF

cat << EOF > debian/build-post-script.sh
#!/bin/sh
find -wholename '*branding/brand.dtd' |xargs sed 's/trademarkInfo.part1.*/trademarkInfo.part1 "">/' -i

for STRING in community.start2 community.mozillaLink community.middle2 community.creditsLink community.end2 contribute.start contribute.getInvolvedLink contribute.end
do
 find -wholename '*browser/aboutDialog.dtd' | xargs sed "s/\$STRING.*/\$STRING \"\">/" -i
done
EOF

changelog  "Compiled for Trisquel"

compile

