#!/bin/sh
#
#    Copyright (C) 2012-2023 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=6
COMPONENT=main

. ./config

#Use custom apt-check to fix motd update notification by striping esm stuff.
cp $DATA/apt_check.py data/apt_check.py
sed -i '/test_motd.py/d' debian/rules
sed -i '/test_package-data-downloader.py/d' debian/rules

rm debian/update-notifier-hp-firmware.conf
sed '/hp-firmware/d' -i debian/update-notifier.install

sed -i "/ubuntu-drivers-common/d" debian/control
echo "exit 0" > data/list-oem-metapackages

# Prevent automated connections
sed '/Update-Package-Lists/s/1/0/' -i debian/10periodic

# Allow to run under KDE
sed '/NotShowIn=KDE/d' -i data/update-notifier.desktop.in

# Actually show the indicator icon
cat << EOF | patch -p1
diff --git a/src/update.c b/src/update.c
index 588fa66..951a24f 100644
--- a/src/update.c
+++ b/src/update.c
@@ -687,7 +687,6 @@ update_check (TrayApplet *ta)
 
       g_child_watch_add (pid, launch_update_manager, NULL);
    }
-   return TRUE;
 
    // if we are already visible, skip the rest
    if(tray_applet_ui_get_visible (ta))
EOF

# Custom icons
cp $DATA/icons/* ./pixmaps/scalable
rm ./pixmaps/{16x16,22x22,24x24,48x48}/ -rf
echo "SUBDIRS = scalable" > pixmaps/Makefile.am
sed '/pixmaps\/..x..\/Makefile/d' -i configure.ac
sed '/usr\/share\/icons\/hicolor\/..x../d' -i debian/update-notifier.install

# Disable livepatch
sed '/livepatch/d' -i debian/update-notifier.install

changelog "Disabled hp-firmware handling and ubuntu-drivers"

compile
