#!/bin/sh
#
#    Copyright (C) 2021 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
EXTERNAL='deb-src http://ftp.debian.org/debian bookworm main'
REPOKEY=0E98404D386FA1D9

. ./config

# Replace deprecated distutils :
# electrum/_vendor/distutils/version.py should be provided by
# /usr/lib/python3/dist-packages/packaging/version.py, confirm.
sed -i 's|python3-distutils,|python3-packaging,|' debian/control
remove_patch Replace-vendored-distutils.patch
patch_p1 $DATA/replace_distutils_by_packaging.patch

changelog "Backported from debian bookworm"

package
