#!/bin/sh
#
#    Copyright (C) 2011  Santiago Rodríguez <aklis@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config



for i in 03_u1_as_default_sync.patch 05_add_start_u1_note.patch 06_use_ubuntu_sso.patch
do
  rm debian/patches/$i
  sed /$i/d debian/patches/series -i
done

sed -i '/libsyncdaemon-1.0-dev/d' debian/control



changelog "Removed UbuntuOne support"
#Closes http://trisquel.info/es/issues/4341

compile

