#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=7
COMPONENT=main

. ./config

for i in 11_add_failsafe_option.patch 02_add_ubuntu_session.patch 12_add_gnome-2d_session.patch
do
    rm debian/patches/$i
    sed "/$i/d" -i debian/patches/series
done

for i in `cat debian/patches/series `
do  
    echo $i
    patch -p1 -N < debian/patches/$i
done

cp data/classic-gnome.session.desktop.in.in data/gnome.session.desktop.in.in
#sed 's/Required=.*/Required=windowmanager;filemanager;/' -i data/classic-gnome.session.desktop.in.in data/gnome.session.desktop.in.in
#mv data/gnome.desktop.in data/gnome-desktop.desktop.in
#replace 'gnome.desktop' 'gnome-desktop.desktop' .

changelog "Rebranded for Trisquel"

compile

