#!/bin/sh
#
#    Copyright (C) 2017-2018  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu artful universe'

. ./config

cat << EOF | patch -p1
--- a/src/orca/orca.py     2015-11-09 09:07:53.000000000 -0500
+++ b/src/orca/orca.py  2018-04-01 00:57:01.426307608 -0400
@@ -40,7 +40,10 @@
 
 try:
     from gi.repository.Gio import Settings
-    a11yAppSettings = Settings(schema_id='org.gnome.desktop.a11y.applications')
+    if os.environ['XDG_SESSION_DESKTOP'] == 'mate':
+      a11yAppSettings = Settings(schema_id='org.mate.applications-at')
+    else:
+      a11yAppSettings = Settings(schema_id='org.gnome.desktop.a11y.applications')
 except:
     a11yAppSettings = None
 
EOF

changelog "Backported from zesty, added support for mate"

compile

