#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2017  Pablo Correa
#    Copyright (C) 2019  Mason Hock <mason@masonhock.com>
#    Copyright (C) 2021 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://ppa.launchpad.net/ltsp/ppa/ubuntu $UPSTREAM main'
REPOKEY=B64988E8F9B7EF68

. ./config

sed -i '/ubuntu-advantage-tools/d' ltsp/client/init/55-cron.sh

replace ubuntu-mate trisquel .
replace ubuntu. trisquel. .
replace Xubuntu Trisquel\ Mini .
replace xubuntu-18.04-desktop-amd64.iso trisquel-mini_9.0_amd64.iso .
replace xubuntu-18.04 trisquel-mini-9.0 .
replace ubuntu-mate-18.04.1-desktop-i386.iso trisquel_9.0_i686.iso .

replace edubuntu trisquel .
replace Edubuntu Trisquel .

changelog "Backported from oficial PPA and some rebranding."

compile
