#!/bin/sh
#
#    Copyright (C) 2019 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu bionic main'
REPOKEY=7638D0442B90D010
BACKPORTS=true
DEPENDS=dh-autoreconf,dh-strip-nondeterminism

. ./config

sed '/dpkg/s/1.19.0.5~/1.18.4/' -i debian/control

changelog "Backported from bionic"

compile
