#!/bin/sh
#
#    Copyright (C) 2009-2018  Ruben Rodriguez <ruben@gnu.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
NETINST=true
. ./config

sed s/ubuntu/trisquel/g -i Makefile
rpl archive.ubuntu.com archive.trisquel.info . -R
rpl ports.ubuntu.com archive.trisquel.info . -R
rpl ubuntu-ports trisquel-ports . -R
rpl Ubuntu Trisquel . -R
rpl /ubuntu/ /trisquel/ . -R
rpl $UPSTREAM $CODENAME . -R
rpl Mirrors.masterlist.ubuntu Mirrors.masterlist.trisquel . -R

rm Mirrors.masterlist.ubuntu
wget https://archive.trisquel.info/trisquel/Mirrors.masterlist -o /dev/null -O Mirrors.masterlist.trisquel

changelog "Rebranded and adapted for Trisquel"
compile
