#!/bin/bash
#
#    Copyright (C) 2008  Peter Stevenson
#    Copyright (C) 2008  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

find |grep getnonfreefonts |xargs rm
sed -i '/rm -f .*getnonfreefonts-sys/d' build/source/texk/texlive/Makefile.in
sed -i '/ln -s .*getnonfreefonts-sys/d' build/source/texk/texlive/Makefile.in
sed -i 's/getnonfreefonts-sys//g' build/source/texk/texlive/Makefile.in
sed -i 's/getnonfreefonts//g' build/source/texk/texlive/Makefile.in
sed -i '/getnonfreefonts/d' debian/patches/series debian/texlive-base-bin.links.dist debian/control texmf/tpm/collection-basicbin.tpm

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${VERSION}'#p' debian/changelog)  "Removed getnonfreefonts font downloader script"

compile

