#!/bin/sh
#
#    Copyright (C) 2025 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

# Debian MATE and Ubuntu Mate both show System Tools, we don't, so we
# customize it.
sed -i "s|^NoDisplay=true|#NoDisplay=true|" data/caja.desktop.in.in

apply_patch_changes

changelog "Apply fallback to fast-content-type patch
Enable display caja desktop for Trisquel menu"

package
