#!/bin/sh
#
#    Copyright (C) 2020  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2026  Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
COMPONENT=main

. ./config

sed '/ubuntu-docs/d' -i debian/control*

# Ubuntu overrides all the files defined in the DO_NOT_INSTALL
# variable by deleting them. Since we don't use ubuntu-docs, we do
# want these files.
sed '/rm \$(DO_NOT_INSTALL); \\/d' -i debian/rules

touch AUTHORS

changelog "Removed ubuntu-docs dependency"

package
