#!/bin/sh
#
#    Copyright (C) 2015  Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C) 2015  Santi Rodriguez <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
. ./config


rm ./debian/control.d/signed-generic

for FILE in debian/control ./debian/control.d/generic ./debian/control.d/lowlatency \
            debian/control.d/generic-lpae
do
sed 's/, linux-firmware//' -i $FILE
sed 's/Linux/Linux-libre/g' -i $FILE
done


sed '/signed/,/EFI/d' -i debian/control

changelog "Removed linux-firmware dependency, renamed release for Trisquel"

compile

