#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

#%FSDG: Remove method to install non-free plugins
rm debian/patches/kubuntu_06_restricted_install.diff
sed /kubuntu_06_restricted_install.diff/d debian/patches/series -i

sed '
s/www.google.com,/duckduckgo.com,/; s/Google/Duck Duck Go/;
s/userbase.kde.org/trisquel.info/; s/UserBase/Trisquel/;
s/www.kubuntuforums.net/store.trisquel.info/; s/Kubuntu Forums/Store/;
s:www.kubuntu.org:trisquel.info/donate/:; s/Kubuntu/Donate/;

s/www.google.com/trisquel.info/;
' debian/patches/kubuntu_05_default_homepages.diff -i

changelog "Compiled for Trisquel"

compile

