#!/bin/sh
#
#    Copyright (C) 2017 Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C) 2019 David Trudgian <dave@trudgian.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
EXTERNAL='deb-src http://ftp.us.debian.org/debian testing main'
REPOKEY=04EE7237B7D453EC

. ./config

sed '/Build-Depends/s/$/, python-configparser/' -i debian/control debian/templates/control.source.in
sed '/Suggests/s/$/\nProvides: linux-firmware/' -i debian/control debian/templates/control.binary.in

changelog "Imported into Trisquel"

md5sum debian/bin/gencontrol.py defines linux-free/defines linux-free/LICENSE debian/changelog debian/templates/control.binary.udeb.in debian/templates/control.binary.in debian/templates/control.source.in > debian/control.md5sum

compile
