#!/bin/sh
#
#    Copyright (C) 2020 Mason Hock <mason@masonhock.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=8.0
CODENAME=flidas
ARCHES="amd64 i386"

NETINST=$PWD/NETINST
mkdir -p $NETINST

bash make-debian-installer

cd PACKAGES/debian-installer/source

for ARCH in $ARCHES; do
    sbuild --dist $CODENAME --arch $ARCH --purge-build never
    cp /var/lib/sbuild/build/$(ls --sort=time /var/lib/sbuild/build/ | head -n1)/*/build/dest/netboot/mini.iso \
       $NETINST/trisquel-netinst_${VERSION}_${ARCH}.iso
done
