#!/bin/sh
#
#    Copyright (C) 2015  Santiago Rodríguez  <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

#Updated copyright file from obtained from
# http://ftp.de.debian.org/debian/pool/main/g/grace/grace_5.1.24-3.debian.tar.xz
# http://anonscm.debian.org/cgit/collab-maint/labplot.git/tree/cephes/COPYING?id=debian/1.6.0.2-3

cp $DATA/copyright debian/copyright
cp $DATA/COPYING.cephes cephes/COPYING

changelog "Updated copyright file"

compile

