#!/bin/sh
#
#    Copyright (C) 2014  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
COMPONENT=main
QUILT=skip

. ./config

for i in git_xsettings_segfaults.patch 90_set_gmenus_xsettings.patch; do
    rm debian/patches/$i
    sed "/$i/d" -i debian/patches/series
done

export QUILT_PATCHES=debian/patches
quilt push -a

# Disable AppMenu completely
#sed '/ShellShowsAppMenu/ s/have_shell/0/' -i plugins/xsettings/gsd-xsettings-manager.c

changelog "Disabled AppMenu and Menubar patch"

compile

