#!/bin/sh
#
#    Copyright (C) 2024  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

sed -i '$d' debian/apparmor-profile
cat  << FIX >> debian/apparmor-profile

  # Add apparmor rule for mate's caja - LP#1798091
  owner /tmp/.mate_desktop_thumbnail* w,
  owner /tmp/mate-desktop-thumbnailer* w,

  # Fix thumbnail issue #915024
  owner @{HOME}/.cache/thumbnails/** rw,
  owner /tmp/atril-thumbnailer* rw,

}
FIX

changelog "Fix LP #1798091 - no pdf thumbnails || Fix Debian #915024 - no pdf thumbnails"

package

