#!/bin/sh
#
#    Copyright (C) 2024 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
BUILD_UNTIL=11.0

. ./config

# 01_Rebuild to use the latest SDL support on aramo.
# 02_SDL_CreateWindowFrom in "display" module
for patch in $(ls -v ${DATA}/*.patch)
do
    echo "Applying $patch"
    patch --no-backup-if-mismatch -Np1 < $patch
done

changelog "Rebuild to use the latest SDL support on aramo. | Fix 'SDL_CreateWindowFrom' in 'display' module"

package
