#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

sed -i 's:<default>s3</default>:<default>file</default>:' data/deja-dup.schemas*
sed -i 's:\(.*/schemas/apps/deja-dup/file/path.*\):\1\n<default>/</default>:' data/deja-dup.schemas*
sed -i 's/Categories.*/Categories=Application;System;Settings/g' data/deja-dup.desktop*

changelog "Compiled for Trisquel"

compile

