#!/bin/sh
#
#    Copyright (C) 2022 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=0
. ./config

#Set default trisquel wallpaper
BUDGIE_WALLP="usr/share/backgrounds/budgie/ubuntu_budgie_wallpaper1.jpg"
TRISQUEL_WALLP="usr/share/backgrounds/$CODENAME.jpg"
grep -lr "$BUDGIE_WALLP" | xargs sed -i "s|$BUDGIE_WALLP|$TRISQUEL_WALLP|g"

#Tweak default handlers
sed -i "s|thunderbird|icedove|g" etc/budgie-desktop/defaults.list
sed -i "s|firefox|abrowser|g" etc/budgie-desktop/defaults.list
sed -i "s|snap-store.*.desktop||g" etc/budgie-desktop/defaults.list

sed -i "s|Launcher=.*|Launcher=|" home-folder/.config/plank/dock1/launchers/budgie-welcome.dockitem
sed -i "s|, 'ubuntu-budgie-welcome_budgie-welcome.desktop'||" schemas/25_budgie-desktop-environment.gschema.override
changelog "Tweak settings and names to match trisquel packages on budgie"

compile
