#!/bin/sh
#
#    Copyright (C) 2011-2016  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=5
NETINST=true

. ./config

#FIXME:T12
# Set version number due to source origin change
export FULLVERSION="$(sed 's|ubuntu0.6||' <<< $FULLVERSION)"

sed 's:Ubuntu:Trisquel\ GNU/Linux:g' -i debian/rules
sed "s|^SSH_EXTRAVERSION.*|SSH_EXTRAVERSION := Trisquel_GNU/Linux_$REVISION-$VERSION|" -i debian/rules

changelog "Rebranded for Trisquel"
head -n1 debian/changelog | grep -q ubuntu && echo "error: update upstream version" && exit

package

