#!/bin/sh
#
#    Copyright (C) 2009-2020 Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C) 2021 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=11
NETINST=true

. ./config

cat << EOF > ${LOCAL_APT}/etc/apt_${CODENAME}.conf
Dir::State "${LOCAL_APT}/var/lib/apt";
Dir::State::status "${LOCAL_APT}/var/lib/dpkg/status";
Dir::Etc::SourceList "${LOCAL_APT}/etc/apt.sources_${CODENAME}.list";
Dir::Etc::SourceParts "";
Dir::Cache "${LOCAL_APT}/var/cache/apt";
pkgCacheGen::Essential "none";
Dir::Etc::Trusted "${LOCAL_APT}/etc/trusted.gpg";
Acquire::ForceIPv4 "true";
EOF

cat << EOF > ${LOCAL_APT}/etc/apt.sources_${CODENAME}.list
deb $LOCALMIRROR $CODENAME main
deb $LOCALMIRROR $CODENAME-updates main
deb $LOCALMIRROR $CODENAME-security main
EOF

find build/pkg-lists -type f | xargs sed -i /media-retriever/d
apt-get update -c ${LOCAL_APT}/etc/apt_${CODENAME}.conf
LASTKERNEL="$(apt-cache madison -c ${LOCAL_APT}/etc/apt_${CODENAME}.conf linux-hwe-5.13-tools-common|\
              grep ${CODENAME}/main|\
              tail -n1|\
              awk '{print$3}'|\
              cut -d. -f1,2,3)"
sed -i "s/^BASEVERSION.*/BASEVERSION = $LASTKERNEL/g" ./build/config/amd64.cfg
sed -i "s/^MEDIUM_SUPPORTED.*/MEDIUM_SUPPORTED = cdrom netboot/g" ./build/config/amd64.cfg

sed -i 's/shim-signed/shim/g' debian/control

cp $DATA/splash.png build/boot/x86/pics/trisquel.png
sed -i 's/ubuntu.png/trisquel.png/g' build/config/x86.cfg

cat << EOF > build/sources.list.udeb.local
deb $LOCALMIRROR $CODENAME main/debian-installer
deb $LOCALMIRROR $CODENAME-updates main/debian-installer
#deb $LOCALMIRROR $CODENAME-security main/debian-installer
EOF

#firmware-linux-free-udeb is missing
cat << EOF >> build/pkg-lists/netboot/common
open-ath9k-htc-firmware-udeb
openfwwf-udeb
EOF

replace "2004-20.." "2004-20$(date +'%y')" .
rpl www.ubuntu.com trisquel.info . -R
rpl ubuntu.com trisquel.info build/boot/ -R
rpl www.ubuntu trisquel build/boot/ -R
rpl \"com/ \"info/ build/boot/ -R
rpl Ubuntu Trisquel . -R
rpl UBUNTU TRISQUEL . -R
rpl TRISQUEL-PT UBUNTU-PT . -R
rpl Canonical Trisquel . -R
rpl Ltd\. GNU/Linux . -R
rpl Trisquel-l10n ubuntu-l10n . -R
rpl "Trisquel Ltd, and Rosetta" "Canonical Ltd, and Rosetta" . -R
rpl ubuntu-keyring trisquel-keyring . -R
rpl ubuntu-archive-keyring trisquel-archive-keyring . -R

sed -i 's/.*SIGNED_IMAGE="$(KERNELNAME_ALT_SUFFIX)".*/'$'\t''efi-image $(TEMP_GRUB_EFI) x86_64-efi x64/' build/config/x86.cfg build/config/arm64.cfg
/bin/sed -i '/KERNELNAME_ALT_SUFFIX = -$(KERNELVERSION)/d' build/config/*.cfg build/config/*/*.cfg

changelog "Rebranded and adapted for Trisquel"
compile

