#!/bin/sh
#
#    Copyright (C) 2019  Mason Hock <mason@masonhock.com>
#    Copyright (C) 2021,2022  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=14

. ./config

sed -i 's/manjaro/trisquel/g' mate-tweak
sed -i 's/Manjaro/Trisquel/g' mate-tweak

# Set icon
sed 's/Icon=.*/Icon=mate-desktop-symbolic/' -i data/mate-tweak.desktop

# Disable composition on llvm
sed 's/Software Rasterizer/Accelerated: no/' -i mate-tweak

# Corrects rendering delay on Pluma, possibly others
sed '/--backend/s/\\/--xrender-sync-fence \\/' -i  marco-wrapper

# Shadow config
sed -i '/shadow-radius/s|12|15|' marco-wrapper
sed -i '/shadow-opacity/s|0.125|0.5|' marco-wrapper
sed -i '/shadow-offset-x/s|-12|-15|' marco-wrapper
sed -i '/shadow-offset-y/s|-12|-15|' marco-wrapper
sed -i 's/Firefox/abrowser/' marco-wrapper
sed -i 's/Ulauncher/icedove/' marco-wrapper

# Transitional dummy marco-compton
rm marco-compton
cat << EOF > marco-compton
#!/bin/sh

# Compton has been replaced by picom (marco-xrender wrapper)

WINDOW_MANAGER=xterm
[ -f /usr/bin/marco ] && WINDOW_MANAGER=marco
[ -f /usr/bin/marco-no-composite ] && WINDOW_MANAGER=marco-no-composite

# Check for hardware acceleration
if glxinfo -B | grep "OpenGL renderer string" | grep -qv llvmpipe ; then
  WINDOW_MANAGER=marco
  # Use marco-glx (picom) on non-intel gpu, if available
  if glxinfo -B | grep -qiv vendor.*intel; then
    if [ -f /usr/bin/picom ] && [ -f /usr/bin/marco-glx ] ; then
            WINDOW_MANAGER=marco-glx
    fi
  fi
fi

gsettings set org.mate.session.required-components windowmanager \$WINDOW_MANAGER

exec \$WINDOW_MANAGER
EOF
chmod 755 marco-compton

# Add Trisquel to layout list
sed 's/fedora/trisquel/g; s/Fedora/Trisquel/' -i mate-tweak

changelog "Add Trisquel as panel layout option"

compile

