#!/bin/sh
#
#    Copyright (C) 2011  Santiago Rodríguez  <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=5
COMPONENT=main

. ./config

patch -p0 < $DATA/asunder.4061-aac.patch
patch -p0 < $DATA/asunder.4061-monkey.patch

changelog "Removed non-free formats. Closes #4061"

#BUG: http://trisquel.info/es/issues/4061

compile

