#!/bin/sh
#
#    Copyright (C) 2019 Mason Hock <mason@masonhock.com>
#    Copyright (C) 2021 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://ppa.launchpad.net/ubuntustudio-ppa/backports/ubuntu $UPSTREAM main '
REPOKEY=F596CF7036BBAA6D
BACKPORTS=true

. ./config

#Set only for amd64 (no docs for armhf), more at
#https://answers.launchpad.net/ubuntu/+source/carla/+question/698213
sed -i "s|Architecture: any|Architecture: amd64 i386|g" debian/control

changelog "Backported from ppa"

compile
