#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

cat << EOF > sweets.recipe
[DEFAULT]
depends   = base/glib >= 2.25.16; base/dbus >= 0.95; base/dbus-glib >= 0.82
 
version   = 0.14.10
stability = stable
 
[Library]
implement = sdk/%(name)s
associate = base/%(name)s
name      = telepathy-glib
summary   = GLib bindings for the Telepathy D-Bus protocol
license   = LGPLv2+
homepage  = http://telepathy.freedesktop.org/
 
requires  = %(depends)s
binding   = LD_LIBRARY_PATH lib; PKG_CONFIG_PATH lib/pkgconfig
 
[Package]
project   = SweetsDistribution
 
[Archive]
arch      = any
 
[Build]
requires  = %(depends)s; base/xsltproc; base/python
            base/pkg-config; base/make; base/gcc-c
clean     = make clean
configure = ./configure
                --prefix=%(PREFIX)s
                --disable-gtk-doc
                CFLAGS="%(CFLAGS)s"
make      = make
install   = make DESTDIR=%(DESTDIR)s install
 
[Source]
source    = telepathy-glib-%(version)s.tar.gz 
EOF

changelog "Compiled for Trisquel On a Sugar TOAST"

compile
