#!/bin/sh
#
#    Copyright (C) 2024  Luis Guzmán <ark@switnet.org>
#    Copyright (C) 2020  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
COMPONENT=main

. ./config

# Do not send hostname to dhcp servers by default
sed 's/send host-name/#send host-name/' -i src/core/dhcp/nm-dhcp-dhclient-utils.c src/core/dhcp/tests/test-dhcp-dhclient.c
sed 's/send fqdn/#send fqdn/' -i src/core/dhcp/nm-dhcp-dhclient-utils.c src/core/dhcp/tests/test-dhcp-dhclient.c
sed '/send host-name/s|added by NetworkManager|Enable at /etc/dhcp/dhclient.conf|' -i src/core/dhcp/tests/test-dhcp-dhclient.c
sed '/send fqdn/s|added by NetworkManager|Enable at /etc/dhcp/dhclient.conf|' -i src/core/dhcp/tests/test-dhcp-dhclient.c
sed '/HOSTNAME4_TAG/s|added by NetworkManager|Enable at /etc/dhcp/dhclient.conf|' -i src/core/dhcp/nm-dhcp-dhclient-utils.c
sed '/FQDN_TAG/s|added by NetworkManager|Enable at /etc/dhcp/dhclient.conf|' -i src/core/dhcp/nm-dhcp-dhclient-utils.c

# Patch debian/rules to match Trisquel on i386 build.
patch_p1 $DATA/define_trisquel_for_i386.patch

changelog "Do not send hostname on dhcp, plus other features"
package

