#!/bin/sh
#
#    Copyright (C) 2015 Andrew M. Lindley <andrew@andrewlindley.co.uk>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

apt-get -y install zip unzip 

. ./config

TEMP=$(mktemp -d --tmpdir)
TEMP_EPUB=$(mktemp --tmpdir --suffix=.zip -u)
EPUB="resources/quick_start.epub" 
unzip $EPUB -d $TEMP
sed 's% or <a href="http://www.bookdesigner.org/wordpress/">Book Designer</a>%%' -i  $TEMP/OEBPS/Text/calibre_quick_start_split_007.xhtml
pushd $TEMP
zip --quiet --recurse-paths $TEMP_EPUB .
pushd
mv $TEMP_EPUB $EPUB
chmod 0644 $EPUB
rm -rf $TEMP
rm -f $TEMP_EPUB

changelog "FSDG compliance #5426"

compile

