#!/bin/sh
#
#    Copyright (C) 2021 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

# This helper can be removed after nabia
#https://bugs.launchpad.net/ubuntu/+source/exiv2/+bug/1941752
#https://invent.kde.org/graphics/gwenview/-/commit/91fcbe9c63c17bc20dbb3dd90e0451997f1c78a6

cat << EOF | patch -p1 
diff -ur source.orig/lib/imagemetainfomodel.cpp source/lib/imagemetainfomodel.cpp
--- source.orig/lib/imagemetainfomodel.cpp	2018-03-01 18:27:16.000000000 -0500
+++ source/lib/imagemetainfomodel.cpp	2021-12-30 16:27:08.620773010 -0500
@@ -290,6 +290,10 @@
                 } else {
                     hash.insert(key, new MetaInfoGroup::Entry(key, label, value));
                 }
+            } catch (const std::out_of_range &error) {
+                // Workaround for https://bugs.launchpad.net/ubuntu/+source/exiv2/+bug/1942799
+                // which was fixed with https://github.com/Exiv2/exiv2/pull/1918/commits/8a1e949bff482f74599f60b8ab518442036b1834
+                qWarning() << "Failed to read some meta info:" << error.what();
             } catch (const Exiv2::Error& error) {
                 qWarning() << "Failed to read some meta info:" << error.what();
             }
EOF


changelog "Fixes LP#1941752"

compile

