#!/bin/sh
#
#    Copyright (C) 2012  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
COMPONENT=main

. ./config

# Remove recommendeds as it points to ubuntu-docs
sed '/ubuntu-docs/d' -i debian/control*

# make the sound daemon compatible with trisquel custom session
replace gnome-fallback gnome-classic .

# Replace logo
replace UbuntuLogo.png TrisquelLogo.png
rm debian/UbuntuLogoBlank.png
cp $DATA/TrisquelLogo.png debian/TrisquelLogoBlank.png
sed 's/ubuntu/trisquel/g; s/Ubuntu/Trisquel/g; s/14.04 LTS/7.0 LTS/' -i debian/rules

# disable ubuntu custom help

for patch in 53_use_ubuntu_help.patch 56_use_ubuntu_info_branding.patch 58_ubuntu_icon_views_redesign.patch; do
    rm ./debian/patches/$patch
    sed /$patch/d -i debian/patches/series
done

# Edit menu selections
cp $DATA/gnomecc.menu.in shell/gnomecc.menu.in

#Remove top menu
sed '/G_ACTION/,/Quit/d' -i shell/control-center.c

replace "Trisquel-Gettext" "Ubuntu-Gettext" .

changelog "Replaced references to gnome-fallback with gnome-classic"

compile

