#!/bin/sh
#
#    Copyright (C) 2024 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

#STAGE-5-DESKTOP|ARTWORK

VERSION=3

. ./config

# Patch PEP440 version.
patch_p1 $DATA/pep440.patch

# Tune default background for kylin
sed -i "s|background=.*|background=\"/usr/share/backgrounds/$CODENAME.jpg\"|" 30_ubuntukylin-wallpapers.gschema.override
sed -i "s|picture-uri=.*|picture-uri=\'file:///usr/share/backgrounds/$CODENAME.jpg\'|" 30_ubuntukylin-wallpapers.gschema.override

# Make sure to review helper on the designed stage prior to release, so it uses
# right artwork when released.
cp $(find $DATA/../trisquel-wallpapers/ -name $CODENAME.*) warty-final-ubuntukylin.jpg

# Add current release wallpaper to any possible xml release kylin-wallpaper file.
for i in $(find -name \*.xml.in)
do
sed -i '/<\/wallpapers>/,/^$/d' $i
cat << EOF >> $i
 <wallpaper>
     <_name>Trisquel $REVISION - ${CODENAME^}</_name>
     <filename>/usr/share/backgrounds/$CODENAME.jpg</filename>
     <options>zoom</options>
     <pcolor>#000000</pcolor>
     <scolor>#000000</scolor>
     <shade_type>solid</shade_type>
 </wallpaper>
</wallpapers>
EOF
done

changelog "Rebranding for trisquel."

package
