#!/bin/sh
#
#    Copyright (C) 2020 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

# We don't want kns discovery, as store.kde.org allows cc-noncomercial
sed '/kns-backend.so/d' -i ./debian/plasma-discover.install

#Disable backend for snap, flatpack and fwupd
sed -i "/DBUILD/s|ON|OFF|g" debian/rules
rm debian/plasma-discover-backend-*.install

#Removing will break build, keeping.
#for i in FlatpakBackend FwupdBackend SnapBackend
#do
#rm -r libdiscover/backends/$i
#done

#Remove binaries
sed -i '/Package: plasma-discover-backend-flatpak/,/^$/d' debian/control
sed -i '/Package: plasma-discover-backend-snap/,/^$/d' debian/control
sed -i '/Package: plasma-discover-backend-fwupd/,/^$/d' debian/control
sed -i '/Package: plasma-discover-flatpak-backend/,/^$/d' debian/control
sed -i '/Package: plasma-discover-snap-backend/,/^$/d' debian/control

# Do not show Plasma Addons in the main menu
/bin/sed -n '0,/^  <\/Menu>/p' -i ./libdiscover/backends/PackageKitBackend/packagekit-backend-categories.xml
echo '</Menu>' >> ./libdiscover/backends/PackageKitBackend/packagekit-backend-categories.xml

#Disable dh_missing fail
sed -i "s|--fail-missing|--list-missing|" debian/rules

changelog "Disable kns, snap and flatpack backend"

compile
