#!/bin/sh
#
#    Copyright (C) 2008-2020  Ruben Rodriguez <ruben@trisquel.info>
#    Copyright (C)      2023  Luis Guzmán <ark@switnet.org>
#    Copyright (C)      2019  Mason Hock <mason@masonhock.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=17

. ./config

rm UpdateManager/Core/LivePatchSocket.py
rm tests/test_livepatch_socket.py
patch --no-backup-if-mismatch -p1 < $DATA/remove-livepatch2.patch
sed -i '/import LivePatchSocket/d' UpdateManager/Dialogs.py
sed -i '/self.check_livepatch_status/d' UpdateManager/Dialogs.py

sed -i "/ubuntu-advantage-tools/d" debian/control

#Closes #12545
patch --no-backup-if-mismatch -p0 < $DATA/trisquel-versions.patch

cp $DATA/index.docbook help/C/index.docbook

# Prevent automated connections
patch --no-backup-if-mismatch -p1 < $DATA/prevent-autoconnection.patch
cat << EOF >> po/es.po

msgid ""
"To prevent unwanted connections to the Internet\n"
"Trisquel will not automatically check for updates\n"
"unless you say so in the Settings panel."
msgstr ""
"Para prevenir conexiones inesperadas a Internet\n"
"Trisquel no descargará actualizaciones automáticamente\n"
"salvo que lo indiques en el panel de Configuración."
EOF

replace internet Internet .
replace Ubuntu Trisquel .
replace TrisquelDistroInfo UbuntuDistroInfo .
replace "Trisquel-Gettext" "Ubuntu-Gettext" .

sed -i 's/Trisquel 20.04 LTS to Trisquel 22.04 LTS/Trisquel 10.0 LTS to Trisquel 11.0 LTS/' HweSupportStatus/consts.py

replace ubuntu-desktop trisquel .
replace kubuntu-desktop triskel .
replace xubuntu-desktop trisquel-mini .
replace edubuntu-desktop toast .

sed '/%s base/ s/name.*/name = "Trisquel base"/' -i ./UpdateManager/Core/UpdateList.py
sed 's_https://changelogs.ubuntu.com/changelogs/pool/_https://packages.trisquel.org/changelogs/pool/_' -i UpdateManager/Core/MyCache.py
sed '/len(changelog) == 0/,/"later."/d' -i UpdateManager/Core/MyCache.py

#Make sure apt_pkg is enabled for prevent-autoconnection.patch to work.
[ -z "$(grep 'import apt_pkg' UpdateManager/UpdateManager.py)" ] && \
sed -i '/import distro_info/i import apt_pkg' UpdateManager/UpdateManager.py

#Make use of new TrisquelDistroInfo
sed -i 's|UbuntuDistroInfo|TrisquelDistroInfo|g' UpdateManager/UpdateManager.py
sed -i 's|UbuntuDistroInfo|TrisquelDistroInfo|g' hwe-support-status
sed -i 's|UbuntuDistroInfo|TrisquelDistroInfo|g' ubuntu-security-status
sed -i 's|UbuntuDistroInfo|TrisquelDistroInfo|g' tests/test_meta_release_core.py
sed -i 's|UbuntuDistroInfo|TrisquelDistroInfo|g' UpdateManager/Core/MetaRelease.py
#Fix partial upgrade button
sed -i '/do-partial-upgrade/s|ubuntu-release|trisquel-release|' UpdateManager/Dialogs.py

#Fix base_uri for trisquel meta-release-lts
sed -i 's|changelogs.ubuntu.com/|archive.trisquel.org/trisquel/|' UpdateManager/Core/MetaRelease.py

# l10n patch fixes
## es.po
patch -p0 < $DATA/l10n/es_po_rev032023.patch

changelog "Compiled for Trisquel"

compile

