#!/bin/sh
#
#    Copyright (C) 2022  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

#STAGE-5-DESKTOP|ARTWORK

VERSION=2
. ./config

# Rebrand and tweak
grep -rl 'font-name='|xargs -r sed -i '/font-name/s|Ubuntu 11|Sans 11|'
replace ubuntu trisquel
replace Ubuntu Trisquel
find -type d |xargs rename s/ubuntu/trisquel/g
find -type f |xargs rename s/ubuntu/trisquel/g

#Themes
rm -r pocillo/IconRequests
cp $DATA/logo-trisquel.svg qogir-theme/src/gnome-shell/logos/
cp $DATA/logo-trisquel.svg qogir-theme/src/gtk/assets/logos/
cp $DATA/trisquel-budgie-logo_128_alpha.png usr/share/plymouth/themes/trisquel-budgie-logo/trisquel-budgie-logo.png
cp $DATA/trisquel-budgie-logo_128_solid.png usr/share/plymouth/themes/trisquel-budgie-logo/trisquel-budgie-logo16.png
cp $DATA/trisquel-budgie-logo_200_solid.png usr/share/plymouth/themes/trisquel-budgie-logo/trisquel-budgie-logo16@2.png
cp $DATA/trisquel-budgie-logo_200_alpha.png usr/share/plymouth/themes/trisquel-budgie-logo/trisquel-budgie-logo@2.png

#Background
sed -i "s|background=.*|background=\'/usr/share/backgrounds/$CODENAME.jpg\'|g" debian/budgie-lightdm-theme.gsettings-override

changelog "Rebuild for trisquel"
package
