#!/bin/sh
#
# Copyright (C) 2012 Grant Houlgate <ghoulgat [at] member [dot] fsf [dot] org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#

VERSION=1

. ./config

#Ugly hack, a blank "white screen" is displayed instead. Low importance package.
sed 's/imgFatalFun->Draw();//g' -i src/HolotzCastle.cpp

changelog "Removed screen showing website advertising non-free games"

package
