#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

cat << EOF > sweets.recipe
[DEFAULT]
depends   = base/glib >= 2.24; base/dbus >= 1.1.0
            base/dbus-glib >= 0.61; base/libxml2
            base/avahi-gobject; base/libsoup; base/uuid; base/sqlite >= 3
            sdk/telepathy-glib >= 0.13.12
 
version   = 0.6.0
stability = stable
 
[Library]
implement = sdk/%(name)s
associate = base/%(name)s
name      = telepathy-salut
summary   = A link-local XMPP connection manager for Telepathy
license   = LGPLv2+
homepage  = http://telepathy.freedesktop.org/
 
requires  = %(depends)s
binding   = PATH libexec; XDG_DATA_DIRS share
 
[Package]
project   = SweetsDistribution
 
[Archive]
arch      = any
 
[Build]
requires  = %(depends)s; base/xsltproc; base/python
            base/pkg-config; base/make; base/gcc-c
clean     = make clean
configure = ./configure
                --prefix=%(PREFIX)s
                --enable-olpc
                --disable-gtk-doc
                --disable-avahi-tests
                CFLAGS="%(CFLAGS)s"
make      = make
install   = make DESTDIR=%(DESTDIR)s install
 
[Source]
source    = telepathy-salut-%(version)s.tar.gz
EOF

changelog "Compiled for Trisquel On a Sugar TOAST"

compile
