#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

rm debian/icons/ubuntu-logo.png
cp $DATA/trisquel-logo.png debian/icons/
cp $DATA/index.html debian/
replace ubuntu-logo trisquel-logo .

# Make the banner be Trisquel GNU/Linux instead of just Trisquel
sed '/^LSB_RELEASE/s/$/_GNU\/Linux/'  -i debian/rules

# Modify the postrm so it picks up the new index.html md5sum as valid
sed '/grep -q "$MD5" <<- EOF/a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ 4dd1085714a2189c372be3e34b7d6c48' -i debian/apache2.postrm

changelog "Compiled for Trisquel"

compile

