#!/bin/sh
#
#    Copyright (C) 2008-2011  Rubén Rodríguez <ruben@trisquel.info>
#    Copyright (C) 2019       Luis Guzman <ark@switnet.org>
#    Copyright (C) 2020       Mason Hock <mason@masonhock.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=5

. ./config

# setup local apt
cat << EOF > $LOCAL_APT/etc/apt.sources.list
deb http://archive.trisquel.info/trisquel etiona main
deb http://archive.trisquel.info/trisquel etiona-updates main
deb http://archive.trisquel.info/trisquel etiona-security main
EOF
apt-key --keyring ${LOCAL_APT}/etc/trusted.gpg adv --keyserver keyserver.ubuntu.com --recv-keys B138CA450C05112F
apt-file update -c $LOCAL_APT/etc/apt.conf

# get list of desktop files
apt-file -c $LOCAL_APT/etc/apt.conf search "/usr/share/applications" | /bin/sed 's| /usr/share/applications/||' > /tmp/desktop-files.list

# get debs
mkdir -p $DATA/debs
for package in $(cat /tmp/desktop-files.list | /bin/sed 's/:.*//'); do
    (
        cd $DATA/debs
        if [ ! -f ${package}_*.deb ]; then
	    apt -c $LOCAL_APT/etc/apt.conf download $package
        fi
    )
done

# extract desktop files
(
    cd $DATA/debs
    for deb in `ls -1 *.deb | /bin/sed 's/\(.*\)\..*/\1/'`; do
	dpkg-deb --fsys-tarfile $deb.deb | tar -xvf - --wildcards ./usr/share/applications/\*.desktop || echo no .desktop files found for $(echo $deb | sed 's/_.*//')
    done
)

# add renamed packages to popcon-data
cp $DATA/popcon-data /tmp/popcon-data
sed -i "/^firefox /a$(grep '^firefox ' /tmp/popcon-data | /bin/sed 's/firefox/abrowser/')" /tmp/popcon-data
sed -i "/^firefox /a$(grep '^firefox ' /tmp/popcon-data | /bin/sed 's/firefox/icecat/')" /tmp/popcon-data
sed -i "/^thunderbird /a$(grep '^thunderbird ' /tmp/popcon-data | /bin/sed 's/thunderbird/icedove/')" /tmp/popcon-data

# create menu data
rm menu-data/*.desktop
for line in $(cat /tmp/desktop-files.list); do
    package=$(echo $line | /bin/sed 's/:.*//')
    desktop=$(echo $line | /bin/sed 's/.*://')
    echo $package:$desktop
    echo $DATA/debs/usr/share/applications/$desktop
    if [ -f $DATA/debs/usr/share/applications/$desktop ]; then
        popcon=1
	vote="$(grep "$package [0-9]" /tmp/popcon-data | head -n1 | awk '{print$2}')" || popcon=0
	if [ $popcon == 1 ]; then
            cp $DATA/debs/usr/share/applications/$desktop menu-data/$package:$(echo $desktop | /bin/sed 's|.*/||g')
            /bin/sed -i $'1 a \n' menu-data/$package:$(echo $desktop | /bin/sed 's|.*/||g')
            /bin/sed -i "2i X-AppInstall-Section=main" menu-data/$package:$(echo $desktop | /bin/sed 's|.*/||g')
            /bin/sed -i "2i X-AppInstall-Popcon=${vote}" menu-data/$package:$(echo $desktop | /bin/sed 's|.*/||g')
            /bin/sed -i "2i X-AppInstall-Package=${package}" menu-data/$package:$(echo $desktop | /bin/sed 's|.*/||g')
        fi
    fi
done

# remove unwanted menu data
(
    cd menu-data
    # only shown in some desktop environments
    rm -rf $(grep -r OnlyShowIn ./usr | awk -F':' '{print $1}' | awk '!NF || !seen[$0]++')
    # no icon defined
    rm -rf $(grep -Lr Icon ./usr | awk -F':' '{print $1}' | awk '!NF || !seen[$0]++')
)

# cleanup
rm -rf $DATA/debs/usr

# remove game subcategories
cp $DATA/applications.menu menu-data/applications.menu

# remove non-free references
sed '/menu-data-codecs/d' -i debian/install
find -name *.desktop -exec sed -i 's/X-AppInstall-Section=universe/X-AppInstall-Section=main/g' {} \;
find -name *buntu*desktop -exec rm {} \;
sed -i '/buntu/d' debian/install

changelog "Replace Ubuntu's application data with Trisquel's"

compile

