#!/bin/sh
#
#    Copyright (C) 2018 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#

VERSION=1

. ./config

sed 's/enable-geoclue2/disable-geoclue2/' -i debian/rules
sed '/geoclue/d' -i debian/control

if [ -f debian/example-redshift.conf ] 
then
  cp debian/example-redshift.conf debian/redshift.conf
  echo "debian/redshift.conf /etc" >> debian/redshift.install
else
  echo "Error, example configuration file not found"
  exit
fi

changelog "Disabled geoclue"

compile
