#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
COMPONENT=main

. ./config

echo "Qhiswa (Cuzco-Collao);1;quz;quz_PE.UTF-8;quz;PE;quz_PE:quz:en_GB:en;kbd=lat0-sun16(utf8)" >> data/languagelist
echo "Aymara;1;aym;aym_PE.UTF-8;aym;PE;aym_PE:aym:en_GB:en;kbd=lat0-sun16(utf8)" >> data/languagelist
echo "quz:quz_PE" >> ./data/langcode2locale
echo "aym:aym_PE" >> ./data/langcode2locale

# Add icedove and abrowser to the supported language-selector apps.
cat << EOF | patch --no-backup-if-mismatch -p1
diff --git a/data/pkg_depends b/data/pkg_depends
index 2ddc062..a81f854 100644
--- a/data/pkg_depends
+++ b/data/pkg_depends
@@ -11,13 +11,14 @@ tr::gvfs:language-pack-gnome-
 # Format: %LCODE% or %LCODE%-%CCODE%
 tr::libreoffice-common:libreoffice-l10n-
 tr::libreoffice-common:libreoffice-help-
-tr::thunderbird:thunderbird-locale-
+tr::icedove:icedove-locale-
+tr::abrowser:abrowser-locale-
 tr::lightning-extension:lightning-extension-locale-
 tr::sunbird:sunbird-locale-
 tr::sword-text-gerlut1545:sword-language-pack-
 tr::gimp:gimp-help-
 tr::evolution:evolution-documentation-
-tr::chromium-browser:chromium-browser-l10n
+#tr::chromium-browser:chromium-browser-l10n
 tr::sylpheed:sylpheed-i18n
 tr::amarok:amarok-help-
 tr::gnome-user-docs:gnome-user-docs-
EOF

changelog "Added quz and aym locales | Added support for abrowser and icedove."

package
