#!/bin/sh
#
#    Copyright (C) 2011-2016  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu disco main universe'
REPOKEY=7638D0442B90D010

. ./config

echo 9 > debian/compat
sed 's/debhelper\ (>= 11/debhelper\ (>=9/' -i debian/control

# https://trisquel.info/en/issues/7753
echo "NoDisplay=true" >> data/midori-private.desktop.in
#sed '/midori-private/d' -i ./po/POTFILES.in
#sed '/Private Shortcut/,1000d' -i data/midori.desktop.in 

rm debian/patches -rf

cat << EOF > debian/Trisquel-config
[settings]
toolbar-style=MIDORI_TOOLBAR_SMALL_ICONS
toolbar-items=TabNew,Back,Forward,ReloadStop,Separator,Homepage,Location,Separator,Search,
homepage=http://trisquel.info/welcome
location-entry-search=https://duckduckgo.com/?t=trisquel&q=!+%s
show-menubar=true

[extensions]
libtoolbar-editor.so=true
EOF

#cat << EOF > debian/config/Trisquel.h
##define DEBIAN_DISTRO_DEFAULT_HOMEPAGE "http://trisquel.info/welcome"
##define DEBIAN_WWW_ALTERNATIVES_PRIORITY 39
#EOF

cat << EOF > data/search

[Duck Duck GO SSL]
name=Duck Duck GO SSL
text=DDG Web Search
uri=https://duckduckgo.com/?t=trisquel&q=%s
icon=
token=d

[Duck Duck GO]
name=Duck Duck GO
text=DDG Web Search
uri=http://duckduckgo.com/?t=trisquel&q=%s
icon=
token=

[Google]
name=Google
text=Web Search
uri=http://www.google.com/search?q=%s
icon=
token=g

[Trisquel]
name=Trisquel 
text=Search Trisquel Site
uri=http://trisquel.info/search/node/%s
icon=
token=t

[Trisquel Packages]
name=Trisquel Packages
text=Search Trisquel Packages
uri=http://packages.trisquel.info/%s
icon=
token=tp

[Wikipedia]
name=Wikipedia
text=The free encyclopedia
uri=http://en.wikipedia.org/wiki/Special:Search/%s
icon=
token=wp

[The Free Dictionary]
name=The Free Dictionary
text=Dictionary, Encyclopedia and Thesaurus
uri=http://www.thefreedictionary.com/%s
icon=
token=fd
EOF

changelog "Search engines configured for Trisquel"

compile

