#!/bin/sh
#
#    Copyright (C) 2008-2011 Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

cp $DATA/usb-creator.svg desktop/usb-creator-gtk.svg
cp $DATA/usb-creator.svg desktop/usb-creator-kde.svg
cp $DATA/usb-creator.svg debian/Ubuntu/usb-creator-gtk.svg
cp $DATA/usb-creator.svg debian/Ubuntu/usb-creator-kde.svg
cp $DATA/usb-creator.svg debian/Debian/usb-creator-gtk.svg
cp $DATA/usb-creator.svg debian/Debian/usb-creator-kde.svg

replace "Ubuntu" "Trisquel" .
replace "Trisquel-Gettext" "Ubuntu-Gettext" .

#disable help button
#sed -i 359s/True/False/ gui/usbcreator-gtk.ui

changelog "Rebranded for Trisquel"

compile

exit 0
if [ $JAILARCH = "i386" ]
then
# Let's build the win32 executable
    apt-get -y --force-yes install mingw32 wine bzr
    sed s:drive_c/windows/system32:drive_c/Python26: -i Makefile
    wget --no-check-certificate https://fedorahosted.org/liveusb-creator/browser/tools/syslinux.exe -O tools/syslinux.exe
    wget --no-check-certificate https://fedorahosted.org/liveusb-creator/browser/tools/dd.exe -O tools/dd.exe
    make build_windows
fi
