#!/bin/sh
#
#    Copyright (C) 2021 Pablo Correa Gómez <ablocorrea@hotmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
EXTERNAL='deb-src https://ppa.launchpadcontent.net/libreoffice/libreoffice-still/ubuntu $UPSTREAM main'
REPOKEY="83FBA1751378B444"

. ./config

# Make sure that Trisquel gets compiled same as Ubuntu
patch -p0 < $DATA/debian-rules.patch

changelog "Backported to get latest version into Trisquel"

compile
