#!/bin/sh
#
#    Copyright (C) 2012-2018  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

# Custom settings
cp $DATA/com.canonical.unity-greeter.gschema.xml data

# Change the sound theme
sed s/ubuntu/freedesktop/g src/unity-greeter.vala -i
sed 's/"system-ready"/"bell"/' src/unity-greeter.vala -i
rm -f src/*.c

# Custom artwork
sed '/logo-bare/d; /rm.*logo.png/d' -i debian/rules
sed '/paint_with_alpha/s/0.5/1.0/' -i src/background.vala
cp $DATA/logo.png data/logo.png
cp $DATA/logo.png .
cp $DATA/logo-bare.png data/logo-bare.png
cp $DATA/cof.png data
cp $DATA/badge.png data/trisquel_badge.png
cp $DATA/badge.png data/unknown_badge.png
replace ubuntu_badge trisquel_badge .

sed '/paint_with_alpha/s/0.4/0.7/' -i src/menubar.vala
sed '/set_source_rgb/s/(0.1, 0.1, 0.1)/(0.0, 0.0, 0.0)/' -i src/menubar.vala
sed '/set_source_rgba/s/(0.1, 0.1, 0.1, 0.4)/(0.0, 0.0, 0.0, 0.7)/' -i src/dash-box.vala

sed '/ttf-ubuntu-font-family/d' -i debian/control

sed '/default_session/ s/ubuntu/trisquel/' -i ./src/user-list.vala
sed '/session_name/ s/ubuntu/trisquel/' -i ./src/settings-daemon.vala

# Custom fonts
replace "Ubuntu 1" "Sans 1" .
replace "Ubuntu Light 1" "Sans 1" .
sed '/set_family/ s/Ubuntu/Sans/' -i src/logo-generator.vala


changelog "Adapted for Trisquel"

compile
