#!/bin/sh
#
#    Copyright (C) 2025 Luis Guzmán <ark@switnet.org>
#    Copyright (C) 2009-2018  Ruben Rodriguez <ruben@gnu.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=9
EXTERNAL='deb-src http://ftp.debian.org/debian trixie main'
REPOKEY=0E98404D386FA1D9
NETINST=true
. ./config

#FIXME: Propose a way to integrate from git and avoid fetching via wget/curl.
Mirrors_masterlist_git="trisquel-packages/-/raw/master/extra/mirrors/Mirrors.masterlist"
patch_p1 $DATA/Makefile_mirrors-masterlist.patch
patch_p1 $DATA/choose-mirror-bin.templates-in.patch

sed -i '/oldstable/d;
        /testing/d;
        /unstable/d;' mirrors.h
sed -i "s|stable|$CODENAME|" mirrors.h
sed -i "s|https://salsa.debian.org.*Mirrors.masterlist.in|https://gitlab.trisquel.org/trisquel/$Mirrors_masterlist_git|" \
    debian/choose-mirror-bin.templates.http-in

replace "_CODENAME_" "$CODENAME"
replace "deb.debian.org" "archive.trisquel.org" .
replace "debian.org" "trisquel.org" .
replace "Debian" "Trisquel" .
replace "/debian/" "/trisquel/" .
sed -i 's|Mirrors.masterlist|Mirrors.masterlist.trisquel|' mirrorlist

rm Mirrors.masterlist
wget https://gitlab.trisquel.org/trisquel/$Mirrors_masterlist_git -o /dev/null -O Mirrors.masterlist.trisquel

changelog "Rebranded and adapted for Trisquel"
package
