#!/bin/sh
#
#    Copyright (C) 2023  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
EXTERNAL='deb-src http://ppa.launchpad.net/libreoffice/ppa/ubuntu $UPSTREAM main'
REPOKEY="83FBA1751378B444"
BACKPORT=true

. ./config

patch --no-backup-if-mismatch -p1 < $DATA/debian-rules_7.3.patch

# Increase CPU usage for amd64 build.
sed -i "/NUM_CPUS=/s|3|7|" debian/rules

changelog "Backport libreoffice fresh into Trisquel"

package
