#!/bin/sh
#
#    Copyright (C) 2011  Santiago Rodríguez <aklis@trisquel.info>
#    Copyright (C) 2018  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
COMPONENT=main

. ./config

for i in 03_magnatune_partner.patch
do
  echo "> Removing patch $i:"
  remove_patch $i
done

changelog "Changed referer for magnatune.
	   #Closes 1718"

package

