#!/bin/sh
#
#    Copyright (C) 2014  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://security.debian.org/ wheezy/updates main'
SIGNKEY="8B48AD6246925553"
LOCALDEPENDS=true
QUILT=skip

. ./config

sed 's/3\.7\.13/3\.7\.9/g' ./debian/patches/wheezy-security/sqlite-dev-revert-version-to-3.7.13.patch debian/patches/series debian/control -i
mv ./debian/patches/wheezy-security/sqlite-dev-revert-version-to-3.7.13.patch ./debian/patches/wheezy-security/sqlite-dev-revert-version-to-3.7.9.patch

sed 's/Provides: mail-reader/Provides: mail-reader, thunderbird/' debian/control -i


#sed '/libffi/d' -i debian/control debian/patches/series
#rm debian/patches/system-libs/Allow-to-build-against-system-libffi.patch

export QUILT_PATCHES=debian/patches
quilt push -a

cat << EOF >> debian/icedove.js

// Trisquel settings
pref("mail.shell.checkDefaultClient", false);
pref("spellchecker.dictionaries.download.url", "http://dictionaries.mozdev.org/installation.html");
pref("extensions.webservice.discoverURL", "https://directory.fsf.org/wiki/Icedove");
pref("extensions.blocklist.enabled", false);
pref("mail.rights.version", 1);
pref("toolkit.telemetry.prompted", 2);
pref("toolkit.telemetry.rejected", true);
EOF

changelog "Imported into Trisquel"

compile
