#!/bin/sh
#
#    Copyright (C) 2012-2020  Ruben Rodriguuez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=7

. ./config

# Only generate the locale selected at boot
sed 's/keep-existing/keep-existing $LANG/' -i scripts/casper-bottom/14locales

# Make sure we disable ureadahead
sed 's/readahead-list/ureadahead/' -i scripts/casper-bottom/25configure_init

# -----
# This patch is no longer a thing on later versions.
# Info at: https://git.launchpad.net/ubuntu/+source/casper/commit/?h=applied/ubuntu/eoan-proposed&id=ce50ef3831a24cb3a5c09c90a98d5a21c20329f4

## Install gsettings for the lightdm user as well
##cat << EOF | patch -p0
##--- scripts/casper-bottom/30accessibility	2017-04-09 15:17:52.538923862 -0400
##+++ scripts/casper-bottom/30accessibility	2017-04-09 20:05:56.018921800 -0400
##@@ -20,6 +20,9 @@
## 		chroot /root /usr/bin/a11y-profile-manager -s \$1 -D /tmp/a11y-profile-casper.d/01-profile
## 		chroot /root /usr/bin/dconf compile /tmp/dconf.\$USERNAME /tmp/a11y-profile-casper.d
## 		mkdir -p /root/home/\$USERNAME/.config/dconf
##+		mkdir -p /root/var/lib/lightdm/.config/dconf
##+                cp /root/tmp/dconf.\$USERNAME /root/var/lib/lightdm/.config/dconf/user
##+		chroot /root chown lightdm.lightdm -R /root/var/lib/lightdm/.config
## 		mv /root/tmp/dconf.\$USERNAME /root/home/\$USERNAME/.config/dconf/user
## 		chroot /root chown \$USERNAME.\$USERNAME -R /home/\$USERNAME/.config
## 		rmdir /root/tmp/a11y-profile-casper.d
##EOF
# -----

rm scripts/casper-premount/10driver_updates
rm scripts/casper-bottom/33enable_apport_crashes


changelog "Compiled for Trisquel"

compile

