#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
COMPONENT=main

. ./config

# No install recommends
sed '/@aptitude=qw/s/aptitude -q/aptitude -q -R/' -i tasksel.pl
sed '/@aptitude="/s/"aptitude"/"aptitude -R"/' -i tasksel.pl
sed '/@apt=qw/s/apt-get -q/apt-get -q --no-install-recommends/' -i tasksel.pl
sed '/@apt="/s/"apt-get"/"apt-get --no-install-recommends"/' -i tasksel.pl

mkdir trisquel-tasks
cp $DATA/* trisquel-tasks
sed s/ubuntu/trisquel/g Makefile -i
sed s/$UPSTREAM/$CODENAME/g Makefile -i
sed 's/\(UFLAVOURS=\).*/\1trisquel-desktop triskel trisquel-mini trisquel-sugar trisquel-edu trisquel-pro trisquel-console/'  Makefile -i

changelog "Added Trisquel's tasks"

compile

