#!/bin/sh
#
#    Copyright (C) 2015  Patrick "P. J." McDermott <pj@pehjota.net>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/>.

VERSION=1

. ./config

sed -i 's/XFVENDOR=.*/XFVENDOR=Trisquel/' debian/rules

cat >debian/vendorinfo <<-'EOF'
	Distributed by Trisquel GNU/Linux developers:
	<mailto:trisquel-devel@listas.trisquel.info>

	Bugs should be reported to Trisquel's issue tracker:
	<http://trisquel.info/en/project/issues/trisquel>
	EOF

changelog "Rebranded for Trisquel"

compile
