#!/bin/sh
#
#    Copyright (C) 2019 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu bionic main'
REPOKEY=7638D0442B90D010
BACKPORTS=true

. ./config

# Build issues
sed '/debhelper/s/10.3/10.2/' -i debian/control
sed '/server.conf/d' -i debian/rules

# Disable sending hostname on DHCP requests
sed '/DHCP_SEND_HOSTNAME/,+1 s/yes/no/' -i libnm-core/nm-setting-ip4-config.c
sed '/NM_SETTING_IP_CONFIG_DHCP_SEND_HOSTNAME/,+1 s/TRUE/FALSE/' -i libnm-core/nm-setting-ip-config.c
sed '/nm_setting_ip_config_get_dhcp_send_hostname/s/NULL/"yes"/' -i src/settings/plugins/ifcfg-rh/nms-ifcfg-rh-writer.c

# Randomize mac addresses
cat << EOF > debian/NetworkManager.conf
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=false

[device]
wifi.scan-rand-mac-address=yes

[connection]
wifi.cloned-mac-address=stable
ethernet.cloned-mac-address=stable
connection.stable-id=\${CONNECTION}/\$(BOOT)
EOF

changelog "Backported from bionic, added privacy features"

compile
