#!/bin/sh
#
#    Copyright (C) 2014  Salman Mohammadi <salman@ubuntu.ir>
#    Copyright (C) 2015  Francisco Javier Parra <franparpe@openmailbox.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

# make the session appear on the login manager
cat << EOF >> debian/unity.install
ubuntu.session /usr/share/gnome-session/sessions
ubuntu.desktop /usr/share/xsessions
EOF

# this creates the session file
cat << EOF > ubuntu.session
[GNOME Session]
Name=Ubuntu
RequiredComponents=unity-settings-daemon;compiz;
DesktopName=Unity
EOF

# this creates the desktop file for the session to exists
cat <<EOF > ubuntu.desktop
[Desktop Entry]
Name=Unity
Comment=This session logs you into Unity
Exec=gnome-session --session=ubuntu
TryExec=unity
Icon=
Type=Application
X-LightDM-DesktopName=Unity
X-Ubuntu-Gettext-Domain=gnome-session-3.0
EOF

# replace Ubuntu branding
cp $DATA/cof.png resources
cp $DATA/launcher_bfb.png resources
cp $DATA/bfb.png tests/data

# replace firefox with abrowser in default launcher; remove amazon from default launcher; replace ubuntu-software-center in default launcher with gnome-app-install
sed -i '
s/firefox/abrowser/g
/ubuntu-amazon-default/d
s/ubuntu-software-center/gnome-app-install/' com.canonical.Unity.gschema.xml

# remove Skype preview
rm dash/previews/Skype.png

# replace default background
sed -i 's/warty-final-ubuntu/belenos/' tests/data/external.gschema.xml

changelog "Replace default applications in launcher, and adapt for Trisquel"

compile
