#!/bin/sh
#
#    Copyright (C) 2026 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

BUILD_UNTIL=11.0
VERSION=0

. ./config

# WARNING: telnetd is not recommended in 2026, especially in production.
# Applying these patches is a proactive mitigation effort for known issues and does not
# endorse continued use of telnetd. The patch co-author recommends deprecating it.

# Remove patch now applied upstream

changelog "Restore build to upstream changes
Apply security patches to mitigate known issues proactively; telnetd is not recommended: avoid in production."

package
