#!/bin/sh
#
#    Copyright (C) 2019 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main '
REPOKEY=8C47BE8E75BCA694

. ./config

sed 's/python3-distutils |//; /python3-repoze.sphinx.autointerface/d' -i debian/control

changelog "Backported from ppa"

compile
