#!/bin/sh
#
#    Copyright (C) 2014 Kouta Ikematsu  <kame55-itasenpara123 at y2.dion.ne.jp>
#    Copyright (C) 2015 Santi Rodriguez <santi at trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Changelog:
#
# 2014/06/24: Fixing "sed" command.
#
#

VERSION=1

. ./config


## Remove non-free score
rm ./mscore/demos/prelude.mscx
sed -i /prelude.mscx/d ./mscore/demos/CMakeLists.txt
echo "#changelog: `env LANG=C date '+%Y-%m%d'` Trisquel-package-helper: Remove prelude.mscx" >> ./mscore/demos/CMakeLists.txt

## Write changelog and compile.
changelog "Removed non-free score"
compile

