#!/bin/sh
#
#    Copyright (C) 2022 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

#Remove snap patches
rm debian/patches/snap_store.diff
sed -i '/snap_store.diff/d' debian/patches/series

#Remove pre-installed menu by gnome-menus' trisquel package
rm data/menus/gnome-flashback-applications.menu
sed -i '/etc\/xdg\/menus/d' debian/gnome-flashback-common.install
sed -i '/gnome-flashback-applications.menu/d' data/menus/Makefile.am
sed -i '/gnome-flashback-applications.menu/d' data/menus/Makefile.in

#Install flashback as default x-session-manager (above 50).
sed -i '/metacity/s|40|60|' debian/gnome-session-flashback.postinst

#Remove hardcoded gsettings
rm  debian/gnome-session-flashback.gsettings-override

changelog "Prevent conflict for pre-installed menu layout."

package
