#!/bin/sh
#
#    Copyright (C) 2023 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
EXTERNAL='deb-src http://ftp.us.debian.org/debian bookworm main'
REPOKEY=04EE7237B7D453EC
. ./config

#Remove symbols missing at trisquel
sed -i '/ZNSt12_Vector_baseIhSaIhEED1Ev@Base/d' debian/libopendht-c2.symbols
sed -i '/ZNSt12_Vector_baseIhSaIhEED2Ev@Base/d' debian/libopendht-c2.symbols
sed -i '/ZNSt14_Function_baseD1Ev@Base/d' debian/libopendht-c2.symbols
sed -i '/ZNSt14_Function_baseD2Ev@Base/d' debian/libopendht-c2.symbols
sed -i '/ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M/d' debian/libopendht-c2.symbols
sed -i '/ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE24_M/d' debian/libopendht-c2.symbols

changelog "Imported into trisquel backports as part of jami dependency."

compile
