#!/bin/sh
#
#    Copyright (C) 2021 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4

. ./config

# Correct event management
patch -p0 < $DATA/t9eximevent.patch

# Fix build issue
cp $DATA/dmarc.patch debian/patches
echo dmarc.patch >> debian/patches/series

cp $DATA/EDITME.exim4-heavy.diff debian/
sed 's/Build-Depends:/Build-Depends: libopendmarc-dev, libspf2-dev, /;/Package: exim4-daemon-heavy/,/Depends/s/Depends: /Depends: libopendmarc2, libspf2-2,/' -i debian/control

sed 's/default-libmysql/libmysql/' -i debian/control

changelog "Enabled DMARC and SPF, Corrects event management"

compile
