#!/bin/sh
#
#    Copyright (C) 2018 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# build-dep tree:
#
# ring
#  restbed libsecp256k1 libupnp
#  ffmpeg
#   libmysofa libopenmpt
#  opendht
#   msgpack-c argon2
#  gnutls28
#   libtasn1-6
#   unbound
#   libunistring
#   softhsm2

VERSION=1
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu cosmic main universe'
REPOKEY=7638D0442B90D010

. ./config

sed 's/--disable-downloads/--disable-downloads --disable-nettle/' -i debian/rules

changelog "Backported from cosmic"

compile
