#!/bin/sh
#
#    Copyright (C) 2012  Santiago Rodríguez  <santi@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
. ./config

#% FREEDOM: Remove menu for non-free drivers
#% CurrentBehaviour: There is a menu option to install non-free drivers (called Guest Additions)
#% ExpectedBehaviour: There is no "Install Guest Additions" menu option
#% Closes: http://trisquel.info/es/issues/4456

FILE=src/VBox/Frontends/VirtualBox/src/runtime/UIMachineMenuBar.cpp
LINENUM=`grep -n 'Simple_InstallGuestTools' $FILE | cut -d\: -f1`

sed -i "$(($LINENUM-1))","$LINENUM"d $FILE

changelog "Removed menu for non-free drivers"

compile

