#!/bin/sh
#
#    Copyright (C) 2022 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
#

VERSION=2
EXTERNAL='deb-src https://ppa.launchpadcontent.net/xuzhen666/gnome-mpv/ubuntu $UPSTREAM main'
REPOKEY=6CAE7FA0B44EEF4EBD4E955F77D026E2EEAD66BD
BUILD_UNTIL=10.0

. ./config

# Disable client-side-decorations by default
sed '/csd-enable/,/summary/s/true/false/' -i data/io.github.celluloid_player.Celluloid.gschema.xml

# Add a quit entry to fullscreen menu
cat << EOF | patch -p1
diff -ur source.orig/src/celluloid-menu.c source/src/celluloid-menu.c
--- source.orig/src/celluloid-menu.c	2020-11-19 03:49:19.955413754 -0500
+++ source/src/celluloid-menu.c	2022-01-27 16:00:07.681380177 -0500
@@ -296,6 +296,7 @@
 			CELLULOID_MENU_ITEM(_("_Preferences"), "win.show-preferences-dialog"),
 			CELLULOID_MENU_ITEM(_("_Keyboard Shortcuts"), "win.show-shortcuts-dialog"),
 			CELLULOID_MENU_ITEM(_("_About Celluloid"), "win.show-about-dialog"),
+			CELLULOID_MENU_ITEM(_("_Quit"), "win.quit"),
 			CELLULOID_MENU_END };
 
 	celluloid_menu_build_menu(menu, entries, TRUE);
EOF

# Fix mpris integration
patch -p1 < $DATA/mpris-v0.22.patch

changelog "Backported from ppa"

compile

