#!/bin/sh
#
#    Copyright (C) 2008-2010  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

for i in 01_lpi.patch 04_new_ubuntu_layout.patch 05_menu_tooltip.patch 06_ubuntu_online_url.patch 07_rosetta_translations_update.patch
do
  rm debian/patches/$i
  sed /$i/d debian/patches/series -i
done

changelog "Compiled for Trisquel"

echo COMPILING ------------------------------------------------------
compile

