#!/bin/sh
#
#    Copyright (C) 2022 Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3

. ./config

# Tune default background for kylin
sed -i "s|background=.*|background=\"/usr/share/backgrounds/$CODENAME.jpg\"|" 30_ubuntukylin-wallpapers.gschema.override
sed -i "s|picture-uri=.*|picture-uri=\'file:///usr/share/backgrounds/$CODENAME.jpg\'|" 30_ubuntukylin-wallpapers.gschema.override

# Copy final artwork from trisquel-packages/$VERSION/trisquel-wallpapers repository.
# Make sure to force helper fail on release update, so it's fixed once the new artwork is released.
cp $DATA/$CODENAME.jpg warty-final-ubuntukylin.jpg

# Add current release wallpaper to any possible xml release kylin-wallpaper file.
for i in $(find -name \*.xml.in)
do
sed -i '/<\/wallpapers>/,/^$/d' $i
cat << EOF >> $i
 <wallpaper>
     <_name>Trisquel $REVISION - ${CODENAME^}</_name>
     <filename>/usr/share/backgrounds/$CODENAME.jpg</filename>
     <options>zoom</options>
     <pcolor>#000000</pcolor>
     <scolor>#000000</scolor>
     <shade_type>solid</shade_type>
 </wallpaper>
</wallpapers>
EOF
done

changelog "Rebranding for trisquel."

package
