#!/bin/sh
#
#    Copyright (C) 2017-2019  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

sed 's/Thunderbird/Icedove/' -i debian/control
sed 's/thunderbird/icedove/' -i debian/control

#Complete dependencies for test suite.
sed -i 's|node-text-table <!nocheck>,|node-text-table <!nocheck>, node-chalk <!nocheck>, node-strip-ansi <!nocheck>,|' debian/control

changelog "Imported into Trisquel"

compile
