#!/bin/sh
#
#    Copyright (C) 2023 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
EXTERNAL='deb-src http://ftp.debian.org/debian bullseye-backports-sloppy main'
REPOKEY=0E98404D386FA1D9
BACKPORT=true

. ./config

#Remove stable backport workaround to keep using libmsgsl-dev 3.0
sed -i 's|\-I\$(CURDIR)/debian||' debian/rules

# Bump VERSION=4 to rebuild against newer libtgowt with openssl 3.0 support.

changelog "Backported from debian bullseye-backports-sloppy | * Bump VERSION=4 to rebuild against libtgowt (0~git20230105.5098730+dfsg-1~bpo11+1+11.0trisquel5) with openssl 3.0 support."

package
