#!/bin/sh
#
#    Copyright (C) 2025  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

##
# This is a rollback for an earlier version, please keep in mind that this
# requires atention for kernel builds on later versions.
##

VERSION=0
. ./config

# Restore udeb build functions for dtbs / firmware packaging on ARM.
patch_p1 $DATA/diff-kernel-wedge-2105_to_296u3.patch
# Set legacy compatibility build (only once).
sed -i '/Build-Depends:/ s|debhelper-compat (= 13)|debhelper-compat (= 9)|' debian/control
rm debian/compat

changelog "Rollback 2.96ubuntu3 on ecne."
package
