#!/bin/sh
#
#    Copyright (C) 2020 Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu focal main universe'
REPOKEY="3B4FE6ACC0B21F32"

. ./config

cat << EOF >> debian/control

Package: python2
Architecture: all
Depends: python2.7
Description: Provides a virtual dependency for python2
 This package provides a dependency to python2.7, needed after backporting dh-python
EOF

changelog "Backported from Focal"

compile
