#!/bin/sh
#
#    Copyright (C) 2008-2020  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=4
COMPONENT=main

. ./config

# No install recommends
sed 's/Install-Recommends=true/Install-Recommends=false/g' -i tasksel.pl

#Remove debian generic-tasks
sed -i '/Package: task-desktop/,/$p/d' debian/control

#Setup trisquel task required customization.
cp -r $DATA/trisquel-tasks .
cp $DATA/Makefile .
cp $DATA/filter-tasks .
sed "/USUITE/s/.*/USUITE=$CODENAME/" Makefile -i

changelog "Added Trisquel's tasks"

compile

