#!/bin/sh
#
#    Copyright (C) 2022  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

##
# This helper is part of a series of packages that are now droppped on upstream
# Ubuntu, therefore in order to build a working debian-installer we now fetch
# such packages from Debian in order to build the required udeb packages.
##

VERSION=2
NETINST=true
BUILD_UNTIL=11.0
. ./config

#FIXME:T12
# Set version number due to source origin change
export FULLVERSION="$(sed 's|ubuntu0.1||' <<< $FULLVERSION)"

# Apply Debian#1035621: ncurses: FTBFS: dh_autoreconf error on various architectures
patch --no-backup-if-mismatch -p1 < $DATA/bbd46b3955647bf401325951d9f31db054e8d889.patch

changelog "Rebuild as udeb dependency for debian-installer and patch dh_autoreconf."
head -n1 debian/changelog | grep -q ubuntu && echo "error: update upstream version" && exit

compile
