#!/bin/sh
#
#    Copyright (C) 2017-2020  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=6

. ./config

find debian/control.d/ -type f | grep -v -e '/generic$' -e '/lowlatency$' -e '/virtual$' |xargs rm

/bin/sed 's/linux-firmware/firmware-linux-free/' -i debian/control ./debian/control.d/*
sed 's/Ubuntu/upstream/' -i debian/control
sed 's/Linux/Linux-libre/g' -i debian/control ./debian/control.d/generic debian/control.d/lowlatency
sed '/Package.*gkeop.*/,/^$/d' -i debian/control

echo '-18.04' > debian/variants

cat << EOF >> debian/control

Package: linux-source-hwe
Architecture: all
Depends: \${misc:Depends}, linux-source-\${kernel-version}
Description: Linux-libre kernel source with upstream patches
 This package will always depend on the latest Linux-libre kernel source code
 available. The upstream patches have been applied.
EOF

changelog "Removed nonfree kernel variants, renamed release for Trisquel"

compile
