#!/bin/sh
#
#    Copyright (C) 2011  Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1
COMPONENT=main

. ./config

#mv debian/patches/01_ubuntu_signature.patch debian/patches/01_trisquel_signature.patch
#sed -i s/01_ubuntu_signature/01_trisquel_signature/ debian/patches/series
#sed -i 's:Ubuntu:Trisquel GNU/Linux:g; s:ubuntu:trisquel:g' debian/patches/01_trisquel_signature.patch debian/signature.py e-util/e-signature-list.c
for i in 09_add_ubuntuone_email.patch 91_add_u1_email_translations.patch
do
    rm debian/patches/$i
    sed -i /$i/d debian/patches/series
done

changelog "Rebranded for Trisquel"

compile

