#!/bin/sh
#
#    Copyright (C) 2013-2015 Andrew M. Lindley <andrew@andrewlindley.co.uk>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

# Trisquel Issue #7969 - package unrar suggests non-free software
sed '/only the non-free "unrar" package can do that/s//see package unar for that/;/Conflicts: unrar-nonfree/d' -i debian/control

changelog "FSDG Compliance #7969"

compile

