#!/bin/sh
#
#    Copyright (C) 2021 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
DEPENDS=distro-info-data

. ./config

#ubuntu-distro-info.c
mv ubuntu-distro-info.c trisquel-distro-info.c
sed -i 's|ubuntu|trisquel|g' trisquel-distro-info.c
sed -i 's|Ubuntu|Trisquel GNU/Linux|g' trisquel-distro-info.c
sed -i 's|UBUNTU|TRISQUEL|g' trisquel-distro-info.c
sed -i 's|,eol-server,eol-esm||' trisquel-distro-info.c
sed -i 's|Ubuntu|Trisquel GNU/Linux|' shell/ubuntu-distro-info.in

# distro-info-util.c
patch --no-backup-if-mismatch -p1 < $DATA/distro-info-util_c.patch

#test-ubuntu-distro-info
cp $DATA/test-trisquel-distro-info .

#python dir
patch --no-backup-if-mismatch -p1 < $DATA/distro_info_py.patch
replace Ubuntu Trisquel
replace ubuntu trisquel
#Maybe too much
#sed -i '/__init__/s|"Trisquel"|"Trisquel GNU/Linux"|' python/distro_info.py
mv python/ubuntu-distro-info python/trisquel-distro-info
cp $DATA/test_distro_info.py python/distro_info_test/

#perl
cp $DATA/test.pl perl/

#shell
mv shell/ubuntu-distro-info.in shell/trisquel-distro-info.in

mv haskell/UbuntuDistroInfo.hs haskell/TrisquelDistroInfo.hs

changelog "Reworking and branding Trisquel GNU/Linux distro info."

compile

