#!/bin/sh
#
#    Copyright (C) 2023 Luis Guzman <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
EXTERNAL='deb-src http://archive.ubuntu.com/ubuntu noble universe'
BACKPORT=true
BUILD_UNTIL=11.0

. ./config

# Fix version number due to early release.
export FULLVERSION="$(sed 's|ubuntu1||' <<< $FULLVERSION)"


changelog "Backported from noble as dependency of libsrtp2 for openssl 3.0 support. || Route backport to upstream ubuntu."
head -n1 debian/changelog | grep -q ubuntu && echo "error: update FULLVERSION value" && exit

package
