#!/bin/sh
#
#    Copyright (C) 2009-2020  Rubén Rodríguez <ruben@gnu.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2
NETINST=true

. ./config

cp $DATA/* kernel/

sed s/KERNEL_PRIO=medium/KERNEL_PRIO=high/g library.sh -i

sed 's/main,restricted/main/; s/ubuntu/trisquel/' -i library.sh ./debian/bootstrap-base.postinst 
sed 's/ubuntu-keyring/trisquel-keyring/' -i ./debian/control

#rpl SECMIRROR/ubuntu MIRROR/trisquel . -R
#rpl /trisquel \$DIRECTORY . -R

changelog "Rebranded and adapted for Trisquel"
compile
