#!/bin/sh
#
#    Copyright (C) 2021 Denis 'GNUtoo' Carikli <GNUtoo@cyberdimension.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=1

. ./config

sed \
    's#^exec java #exec /usr/lib/jvm/java-11-openjdk-amd64/bin/java #' \
    -i ./debian/scripts/proguard

sed 's/default-jre/openjdk-11-jre/g' -i debian/control

changelog "Always use Java 11 because Trisquel 9 also has Java 8 which can't run classes compiled by Java 11"

compile
