#!/bin/sh
#
#    Copyright (C) 2008-2011 Rubén Rodríguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=2

. ./config

cp $DATA/usb-creator.svg desktop/usb-creator-gtk.svg
cp $DATA/usb-creator.svg desktop/usb-creator-kde.svg
cp $DATA/usb-creator.svg debian/Ubuntu/usb-creator-gtk.svg
cp $DATA/usb-creator.svg debian/Ubuntu/usb-creator-kde.svg
cp $DATA/usb-creator.svg debian/Debian/usb-creator-gtk.svg
cp $DATA/usb-creator.svg debian/Debian/usb-creator-kde.svg

replace "Ubuntu" "Trisquel" .
replace "Trisquel-Gettext" "Ubuntu-Gettext" .

sed -i '/install Trisquel from a removable disk/s|Trisquel|your OS|' gui/usbcreator-*.ui
sed -i '/You may now run Trisquel on other computers/s|Trisquel|your OS|' gui/usbcreator-gtk.ui \
       po/usbcreator.pot
sed -i '/takes an Trisquel CD image/s|Trisquel|OS|' man/usb-creator-*.8
sed -i "s|'Trisquel.')|'your OS.')|" usbcreator/frontends/kde/frontend.py

# Set right issues url
sed -i "s|<https://launchpad.net/ubuntu/.*filebug>|<https://gitlab.trisquel.org/trisquel/package-helpers/-/issues/>|; \
        s|Trisquel Launchpad|Trisquel's issues tracker|" man/usb-creator-*.8

# Trisquel l10n modifications using git patches.
for patch in $(ls -v ${DATA}/l10n/*.patch)
do
    echo "> Applying $patch"
    patch --no-backup-if-mismatch -Np1 < $patch
done

#disable help button
#sed -i 359s/True/False/ gui/usbcreator-gtk.ui

changelog "Rebranded for Trisquel"

compile

exit 0
if [ $JAILARCH = "i386" ]
then
# Let's build the win32 executable
    apt-get -y --force-yes install mingw32 wine bzr
    sed s:drive_c/windows/system32:drive_c/Python26: -i Makefile
    wget --no-check-certificate https://fedorahosted.org/liveusb-creator/browser/tools/syslinux.exe -O tools/syslinux.exe
    wget --no-check-certificate https://fedorahosted.org/liveusb-creator/browser/tools/dd.exe -O tools/dd.exe
    make build_windows
fi
