#!/bin/sh
#
#    Copyright (C) 2025  Luis Guzmán <ark@switnet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=5

. ./config

# Patch trisquel feeds
patch_p1 $DATA/trisquel_feeds.patch
# Remove upstream one.
remove_patch kubuntu_debianize_akregator_default.diff

# Prevent ppc64el arch since qtwebengine is not build for ppc64el either.
sed -i 's|Architecture: any|Architecture: amd64 arm64 armhf i386|g' debian/control

changelog "Patched feeds for Trisquel"

package
