#!/bin/sh
#
#    Copyright (C) 2013-2016  Ruben Rodriguez <ruben@trisquel.info>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

VERSION=3
. ./config

for patch in 16_unity_new_documents.patch; do
  rm debian/patches/$patch
  sed "/$patch/d" -i debian/patches/series
done

check_file() {
if [ ! -f $1 ]; then
    echo " $1 doesn't exist removing from debian/docs"
    sed -i "/^$1/d" debian/docs
fi
}

echo "Checking for necessary files to install by debian/docs."
while read i
do
    check_file $i
done < debian/docs


changelog "Revert from using ubuntu-help to default gnome-help"
compile

