#!/bin/sh

WINDOW_MANAGER=xterm
[ -f /usr/bin/marco ] && WINDOW_MANAGER=marco
[ -f /usr/bin/marco-no-composite ] && WINDOW_MANAGER=marco-no-composite

if glxinfo | grep -q Accelerated.*yes  && [ -f /usr/bin/picom ] && [ -f /usr/bin/marco-xrender ] ; then
    WINDOW_MANAGER=marco-xrender
fi

gsettings set org.mate.session.required-components windowmanager $WINDOW_MANAGER

exec $WINDOW_MANAGER
