#!/bin/sh

PREREQ=""
DESCRIPTION="Enabling Abrowser apparmor profile..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

chroot /root /sbin/apparmor_parser -r /etc/apparmor.d/abrowser

log_end_msg
