#!/bin/sh

PREREQ=""
DESCRIPTION="Enabling Abrowser apparmor profile..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat << 'EOF' > /root/etc/rc.local
#!/bin/sh
# Enable apparmor profile during live session to allow Abrowser to create user namespaces
BROWSERS="abrowser icecat"
for browser in $BROWSERS; do
[ -d /rofs ] && apparmor_parser -a /etc/apparmor.d/$browser
done
EOF
chmod 755 /root/etc/rc.local

log_end_msg
