#!/bin/sh

PREREQ=""
DESCRIPTION="Enabling IceCat apparmor profile..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat << EOF > /root/etc/rc.local
#!/bin/sh
# Enable apparmor profile during live session to allow IceCat to create user namespaces
[ -d /rofs ] && apparmor_parser -a /etc/apparmor.d/icecat
EOF
chmod 755 /root/etc/rc.local

log_end_msg
