#!/bin/sh

set -e

if [ "$1" = "purge" ]; then
    # remove the cached application data
    rm -f /var/cache/app-install/*
fi


# Automatically added by dh_scrollkeeper
if [ "$1" = "remove" ] && which scrollkeeper-update >/dev/null 2>&1; then
	scrollkeeper-update -q
fi
# End automatically added section
# Automatically added by dh_gconf
if [ "$1" = purge ]; then
	OLD_DIR=/etc/gconf/schemas
	SCHEMA_FILES="gnome-app-install.schemas "
	if [ -d $OLD_DIR ]; then
		for SCHEMA in $SCHEMA_FILES; do
			rm -f $OLD_DIR/$SCHEMA
		done
		rmdir -p --ignore-fail-on-non-empty $OLD_DIR
	fi
fi
# End automatically added section
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/hicolor
fi
# End automatically added section

